# Generated by Django 4.2.20 on 2025-04-21 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tourism.tourismplace'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_of_visit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
