INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(1, 'Red Fort', 'UNESCO World Heritage Site built in the 17th century by Shah Jahan. This massive red sandstone fort is known for its stunning architecture and historical significance.', '/media/place_images/red_fort.jpg'),
(1, 'India Gate', 'A war memorial dedicated to soldiers who died in World War I. This iconic archway stands at the center of New Delhi and is surrounded by lush lawns.', '/media/place_images/india_gate.jpg'),
(1, 'Qutub Minar', 'UNESCO World Heritage Site featuring the world''s tallest brick minaret. This 73-meter tall tower was built in 1193 and is surrounded by ancient ruins.', '/media/place_images/qutub_minar.jpg'),
(1, 'Humayun''s Tomb', 'UNESCO World Heritage Site and the first garden-tomb on the Indian subcontinent. This magnificent structure inspired the Taj Mahal.', '/media/place_images/humayuns_tomb.jpg'),
(1, 'Lotus Temple', 'A Bahá''í House of Worship notable for its flowerlike shape. The temple is made of pure white marble and is surrounded by nine pools and gardens.', '/media/place_images/lotus_temple.jpg'),
(1, 'Akshardham Temple', 'A Hindu temple complex showcasing millennia of traditional Hindu and Indian culture. Features intricate carvings, a musical fountain, and exhibitions.', '/media/place_images/akshardham_temple.jpg'),
(1, 'Jama Masjid', 'India''s largest mosque, built by Emperor Shah Jahan. Can accommodate up to 25,000 worshippers and features three gates, four towers, and two minarets.', '/media/place_images/jama_masjid.jpg'),
(1, 'Chandni Chowk', 'One of the oldest and busiest markets in Old Delhi. Known for its narrow winding lanes full of shops selling spices, textiles, jewelry, and street food.', '/media/place_images/chandni_chowk.jpg'),
(1, 'Rashtrapati Bhavan', 'The official residence of the President of India. This massive building has 340 rooms spread over 4 floors and is surrounded by the Mughal Gardens.', '/media/place_images/rashtrapati_bhavan.jpg'),
(1, 'National Museum', 'Houses over 200,000 artworks spanning more than 5,000 years of Indian cultural heritage. Features artifacts from the Indus Valley Civilization to modern times.', '/media/place_images/national_museum.jpg'),
(1, 'Jantar Mantar', 'An 18th-century astronomical observatory built by Maharaja Jai Singh II. Features masonry instruments used to predict eclipses and track stars.', '/media/place_images/jantar_mantar.jpg'),
(1, 'Lodhi Gardens', 'A historical park containing architectural works of the 15th-century Lodhi dynasty. Spans 90 acres and features tombs, mosques, and gardens.', '/media/place_images/lodhi_gardens.jpg'),
(1, 'Gurudwara Bangla Sahib', 'One of the most prominent Sikh houses of worship in Delhi. Known for its association with the eighth Sikh Guru, Guru Har Krishan.', '/media/place_images/gurudwara_bangla_sahib.jpg'),
(1, 'Hauz Khas Complex', 'A historic complex dating back to the 13th century. Features a water tank, Islamic seminary, mosque, pavilions, and a royal tomb.', '/media/place_images/hauz_khas_complex.jpg'),
(1, 'National Rail Museum', 'Showcases the rail heritage of India. Exhibits include vintage locomotives, coaches, saloons, and artifacts from the 1800s onward.', '/media/place_images/national_rail_museum.jpg'),
(1, 'Parliament House', 'A circular colonnaded building that houses the Parliament of India. An impressive example of British colonial architecture.', '/media/place_images/parliament_house.jpg'),
(1, 'Connaught Place', 'One of the largest financial, commercial, and business centers in New Delhi. Features a circular design with Georgian-style architecture.', '/media/place_images/connaught_place.jpg'),
(1, 'Gandhi Smriti', 'The location where Mahatma Gandhi spent the last 144 days of his life and was assassinated. Now a museum dedicated to his life and principles.', '/media/place_images/gandhi_smriti.jpg'),
(1, 'Purana Qila', 'An ancient fortress believed to be built on the site of Indraprastha, the legendary city from the Mahabharata. Features massive walls and three arched gateways.', '/media/place_images/purana_qila.jpg'),
(1, 'National Zoological Park', 'A 176-acre zoo home to over 1,300 animals representing around 130 species. Features a 16th-century citadel and spacious enclosures.', '/media/place_images/national_zoological_park.jpg');

-- Hotels for Delhi
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(1, 'The Taj Mahal Hotel', '1, Man Singh Road, New Delhi, 110011', 4.9, 15000.00, '/media/hotel_images/taj_mahal_hotel.jpg'),
(1, 'The Imperial', 'Janpath Lane, Connaught Place, New Delhi, 110001', 4.8, 18000.00, '/media/hotel_images/the_imperial.jpg'),
(1, 'The Leela Palace', 'Diplomatic Enclave, Chanakyapuri, New Delhi, 110023', 4.9, 20000.00, '/media/hotel_images/leela_palace.jpg'),
(1, 'ITC Maurya', 'Sardar Patel Marg, Diplomatic Enclave, New Delhi, 110021', 4.7, 14000.00, '/media/hotel_images/itc_maurya.jpg'),
(1, 'The Oberoi', 'Dr. Zakir Hussain Marg, New Delhi, 110003', 4.8, 17000.00, '/media/hotel_images/the_oberoi.jpg'),
(1, 'The Claridges', '12, Dr APJ Abdul Kalam Road, New Delhi, 110011', 4.6, 12000.00, '/media/hotel_images/the_claridges.jpg'),
(1, 'Shangri-La Eros Hotel', '19, Ashoka Road, Connaught Place, New Delhi, 110001', 4.7, 13000.00, '/media/hotel_images/shangri_la_eros.jpg'),
(1, 'The Lodhi', 'Lodhi Road, New Delhi, 110003', 4.8, 16000.00, '/media/hotel_images/the_lodhi.jpg'),
(1, 'Hyatt Regency Delhi', 'Bhikaji Cama Place, Ring Road, New Delhi, 110066', 4.5, 11000.00, '/media/hotel_images/hyatt_regency_delhi.jpg'),
(1, 'The Roseate', 'National Highway 8, New Delhi, 110037', 4.6, 13500.00, '/media/hotel_images/the_roseate.jpg'),
(1, 'JW Marriott Hotel', 'Asset Area 4, Hospitality District, Aerocity, New Delhi, 110037', 4.6, 12500.00, '/media/hotel_images/jw_marriott.jpg'),
(1, 'Le Meridien New Delhi', 'Windsor Place, Janpath, New Delhi, 110001', 4.5, 10500.00, '/media/hotel_images/le_meridien.jpg'),
(1, 'Radisson Blu Plaza', 'National Highway 8, New Delhi, 110017', 4.4, 9500.00, '/media/hotel_images/radisson_blu_plaza.jpg'),
(1, 'The Park', '15, Parliament Street, New Delhi, 110001', 4.3, 8500.00, '/media/hotel_images/the_park.jpg'),
(1, 'Sheraton New Delhi Hotel', 'District Centre, Saket, New Delhi, 110017', 4.4, 9000.00, '/media/hotel_images/sheraton_new_delhi.jpg'),
(1, 'Crowne Plaza New Delhi Okhla', 'Plot No. 1, Community Centre Phase 1, Okhla, New Delhi, 110020', 4.3, 8000.00, '/media/hotel_images/crowne_plaza_okhla.jpg'),
(1, 'The Lalit New Delhi', 'Barakhamba Avenue, Connaught Place, New Delhi, 110001', 4.5, 10000.00, '/media/hotel_images/the_lalit.jpg'),
(1, 'Taj Palace', '2, Sardar Patel Marg, Diplomatic Enclave, New Delhi, 110021', 4.7, 13000.00, '/media/hotel_images/taj_palace.jpg'),
(1, 'Pride Plaza Hotel', 'Asset 5A, Hospitality District, Aerocity, New Delhi, 110037', 4.2, 7500.00, '/media/hotel_images/pride_plaza.jpg'),
(1, 'Vivanta New Delhi', 'Surajkund, NCR, New Delhi, 121001', 4.4, 9000.00, '/media/hotel_images/vivanta_new_delhi.jpg');

-- Venues for Delhi
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(1, 'Taj Palace Ballroom', '2, Sardar Patel Marg, Diplomatic Enclave, New Delhi, 110021', 1000, 300000.00, '/media/venue_images/taj_palace_ballroom.jpg'),
(1, 'The Leela Convention Centre', 'Diplomatic Enclave, Chanakyapuri, New Delhi, 110023', 1500, 400000.00, '/media/venue_images/leela_convention_centre.jpg'),
(1, 'ITC Grand Bharat', 'P5 Hasanpur, DLF Phase 5, New Delhi, 122011', 800, 350000.00, '/media/venue_images/itc_grand_bharat.jpg'),
(1, 'The Imperial Grand Ballroom', 'Janpath Lane, Connaught Place, New Delhi, 110001', 600, 280000.00, '/media/venue_images/imperial_grand_ballroom.jpg'),
(1, 'The Ashok Hotel Convention Hall', '50-B, Diplomatic Enclave, Chanakyapuri, New Delhi, 110021', 1200, 320000.00, '/media/venue_images/ashok_hotel_convention.jpg'),
(1, 'Hyatt Regency Conference Centre', 'Bhikaji Cama Place, Ring Road, New Delhi, 110066', 900, 270000.00, '/media/venue_images/hyatt_regency_conference.jpg'),
(1, 'Pragati Maidan Exhibition Centre', 'Mathura Road, New Delhi, 110002', 5000, 500000.00, '/media/venue_images/pragati_maidan.jpg'),
(1, 'The Oberoi Grand Ballroom', 'Dr. Zakir Hussain Marg, New Delhi, 110003', 700, 290000.00, '/media/venue_images/oberoi_grand_ballroom.jpg'),
(1, 'India Habitat Centre', 'Lodhi Road, New Delhi, 110003', 1100, 280000.00, '/media/venue_images/india_habitat_centre.jpg'),
(1, 'Siri Fort Auditorium', 'Asian Games Village Complex, Siri Fort, New Delhi, 110049', 2000, 350000.00, '/media/venue_images/siri_fort_auditorium.jpg'),
(1, 'JW Marriott Grand Ballroom', 'Asset Area 4, Hospitality District, Aerocity, New Delhi, 110037', 950, 310000.00, '/media/venue_images/jw_marriott_grand_ballroom.jpg'),
(1, 'Talkatora Indoor Stadium', 'President''s Estate, Mother Teresa Crescent, New Delhi, 110004', 3000, 400000.00, '/media/venue_images/talkatora_stadium.jpg'),
(1, 'Shangri-La Grand Ballroom', '19, Ashoka Road, Connaught Place, New Delhi, 110001', 850, 300000.00, '/media/venue_images/shangri_la_grand_ballroom.jpg'),
(1, 'Thyagaraj Sports Complex', 'INA Colony, New Delhi, 110023', 5500, 450000.00, '/media/venue_images/thyagaraj_sports_complex.jpg'),
(1, 'Le Meridien Conference Hall', 'Windsor Place, Janpath, New Delhi, 110001', 700, 260000.00, '/media/venue_images/le_meridien_conference.jpg'),
(1, 'Jawaharlal Nehru Stadium', 'Lodhi Road, New Delhi, 110003', 60000, 800000.00, '/media/venue_images/jawaharlal_nehru_stadium.jpg'),
(1, 'Aerocity Event Hub', 'Hospitality District, Aerocity, New Delhi, 110037', 1200, 330000.00, '/media/venue_images/aerocity_event_hub.jpg'),
(1, 'The Lalit Poolside Lawn', 'Barakhamba Avenue, Connaught Place, New Delhi, 110001', 500, 220000.00, '/media/venue_images/lalit_poolside_lawn.jpg'),
(1, 'Delhi Gymkhana Club', '2, Safdarjung Road, New Delhi, 110011', 400, 200000.00, '/media/venue_images/delhi_gymkhana_club.jpg'),
(1, 'National Science Centre', 'Near Gate No. 1, Pragati Maidan, Bhairon Road, New Delhi, 110001', 800, 250000.00, '/media/venue_images/national_science_centre.jpg');

-- ==================== MUMBAI ====================
-- Tourism Places for Mumbai
INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(2, 'Gateway of India', 'An iconic arch monument built during the 20th century overlooking the Arabian Sea. This monument was erected to commemorate the landing of King George V and Queen Mary in 1911.', '/media/place_images/gateway_of_india.jpg'),
(2, 'Marine Drive', 'A 3.6-kilometer-long boulevard in South Mumbai that curves along the coastline. Also known as the Queen''s Necklace because the street lights resemble a string of pearls when viewed from above at night.', '/media/place_images/marine_drive.jpg'),
(2, 'Elephanta Caves', 'UNESCO World Heritage Site located on Elephanta Island in Mumbai Harbour. The island features ancient cave temples carved out of rock and dedicated to Lord Shiva.', '/media/place_images/elephanta_caves.jpg'),
(2, 'Chhatrapati Shivaji Terminus', 'A historic railway station and UNESCO World Heritage Site known for its Victorian Gothic Revival architecture. One of the busiest railway stations in India.', '/media/place_images/chhatrapati_shivaji_terminus.jpg'),
(2, 'Juhu Beach', 'One of the most famous beaches in Mumbai, known for its food stalls, celebrities'' homes, and scenic views of the Arabian Sea. A popular recreational spot.', '/media/place_images/juhu_beach.jpg'),
(2, 'Siddhivinayak Temple', 'A Hindu temple dedicated to Lord Ganesha. One of the richest temples in Mumbai and visited by people of all faiths.', '/media/place_images/siddhivinayak_temple.jpg'),
(2, 'Colaba Causeway', 'A commercial street and a major causeway in Colaba. Known for its shopping, restaurants, and famous landmarks including Leopold Cafe and Taj Mahal Palace Hotel.', '/media/place_images/colaba_causeway.jpg'),
(2, 'Haji Ali Dargah', 'A mosque and dargah (tomb) located on an islet off the coast of Worli. Contains the tomb of Sayed Peer Haji Ali Shah Bukhari.', '/media/place_images/haji_ali_dargah.jpg'),
(2, 'Film City', 'An integrated film studio complex with several recording rooms, gardens, lakes, theaters, and grounds. The hub of the Bollywood film industry.', '/media/place_images/film_city.jpg'),
(2, 'Bandra-Worli Sea Link', 'An 8-lane cable-stayed bridge that links Bandra in the Western Suburbs to Worli in South Mumbai. One of the most recognizable landmarks of Mumbai.', '/media/place_images/bandra_worli_sea_link.jpg'),
(2, 'Sanjay Gandhi National Park', 'A large protected area in the northern part of Mumbai city. Known for its biodiversity, ancient Kanheri caves, and a small population of leopards.', '/media/place_images/sanjay_gandhi_national_park.jpg'),
(2, 'Chowpatty Beach', 'A public beach along the Marine Drive. Famous for its Ganesh Chaturthi celebrations and a variety of street foods.', '/media/place_images/chowpatty_beach.jpg'),
(2, 'Mahalaxmi Temple', 'One of the most famous temples of Mumbai dedicated to Mahalakshmi, the goddess of wealth and wisdom. Located on Bhulabhai Desai Road.', '/media/place_images/mahalaxmi_temple.jpg'),
(2, 'Nehru Science Centre', 'India''s largest interactive science center located in Worli. Features over 500 hands-on and interactive science exhibits.', '/media/place_images/nehru_science_centre.jpg'),
(2, 'Hanging Gardens', 'Also known as Pherozeshah Mehta Gardens, these terraced gardens provide panoramic views of the Arabian Sea. Located at the top of Malabar Hill.', '/media/place_images/hanging_gardens.jpg'),
(2, 'Kanheri Caves', 'Ancient Buddhist caves located within the Sanjay Gandhi National Park. The caves, dating from the 1st century BCE to the 10th century CE, served as Buddhist monasteries.', '/media/place_images/kanheri_caves.jpg'),
(2, 'Jehangir Art Gallery', 'An art gallery located in South Mumbai. Built in 1952, it is one of the most prestigious art galleries in India.', '/media/place_images/jehangir_art_gallery.jpg'),
(2, 'Taraporewala Aquarium', 'India''s oldest aquarium located on Marine Drive. Houses marine and freshwater fishes.', '/media/place_images/taraporewala_aquarium.jpg'),
(2, 'Royal Opera House', 'The only surviving opera house in India, located on Charni Road. Recently restored to its former glory, it now hosts performances and cultural events.', '/media/place_images/royal_opera_house.jpg'),
(2, 'Mani Bhavan', 'A museum and historical building dedicated to Gandhi, where he stayed during his visits to Mumbai between 1917 and 1934.', '/media/place_images/mani_bhavan.jpg');

-- Hotels for Mumbai
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(2, 'The Taj Mahal Palace', 'Apollo Bunder, Colaba, Mumbai, 400001', 4.9, 25000.00, '/media/hotel_images/taj_mahal_palace.jpg'),
(2, 'The Oberoi Mumbai', 'Nariman Point, Mumbai, 400021', 4.8, 22000.00, '/media/hotel_images/oberoi_mumbai.jpg'),
(2, 'Four Seasons Hotel Mumbai', '1/136, Dr. E. Moses Road, Worli, Mumbai, 400018', 4.7, 18000.00, '/media/hotel_images/four_seasons_mumbai.jpg'),
(2, 'Trident Nariman Point', 'Nariman Point, Mumbai, 400021', 4.6, 16000.00, '/media/hotel_images/trident_nariman_point.jpg'),
(2, 'JW Marriott Mumbai Juhu', 'Juhu Tara Road, Juhu Beach, Mumbai, 400049', 4.7, 17000.00, '/media/hotel_images/jw_marriott_juhu.jpg'),
(2, 'The St. Regis Mumbai', '462, Senapati Bapat Marg, Lower Parel, Mumbai, 400013', 4.8, 20000.00, '/media/hotel_images/st_regis_mumbai.jpg'),
(2, 'Grand Hyatt Mumbai', 'Off Western Express Highway, Santacruz East, Mumbai, 400055', 4.6, 15000.00, '/media/hotel_images/grand_hyatt_mumbai.jpg'),
(2, 'Taj Lands End', 'Bandstand, Bandra West, Mumbai, 400050', 4.7, 18000.00, '/media/hotel_images/taj_lands_end.jpg'),
(2, 'The Leela Mumbai', 'Sahar, Andheri East, Mumbai, 400059', 4.6, 16000.00, '/media/hotel_images/leela_mumbai.jpg'),
(2, 'ITC Grand Central', '287, Dr. Babasaheb Ambedkar Road, Parel, Mumbai, 400012', 4.5, 14000.00, '/media/hotel_images/itc_grand_central.jpg'),
(2, 'Sofitel Mumbai BKC', 'C-57, Bandra Kurla Complex, Bandra East, Mumbai, 400051', 4.6, 15500.00, '/media/hotel_images/sofitel_mumbai.jpg'),
(2, 'Sahara Star', 'Opposite Domestic Airport, Vile Parle East, Mumbai, 400099', 4.4, 12000.00, '/media/hotel_images/sahara_star.jpg'),
(2, 'The Westin Mumbai Garden City', 'International Business Park, Oberoi Garden City, Goregaon East, Mumbai, 400063', 4.5, 13500.00, '/media/hotel_images/westin_mumbai.jpg'),
(2, 'Novotel Mumbai Juhu Beach', 'Balraj Sahani Marg, Juhu Beach, Mumbai, 400049', 4.3, 11000.00, '/media/hotel_images/novotel_juhu.jpg'),
(2, 'Vivanta President', '90, Cuffe Parade, Mumbai, 400005', 4.4, 12500.00, '/media/hotel_images/vivanta_president.jpg'),
(2, 'InterContinental Marine Drive', '135, Marine Drive, Mumbai, 400020', 4.5, 14000.00, '/media/hotel_images/intercontinental_marine_drive.jpg'),
(2, 'Radisson Blu Mumbai International Airport', 'Plot No 33, Andheri Kurla Road, Marol, Andheri East, Mumbai, 400059', 4.2, 9500.00, '/media/hotel_images/radisson_blu_airport.jpg'),
(2, 'Hyatt Regency Mumbai', 'Sahar Airport Road, Andheri East, Mumbai, 400099', 4.4, 12000.00, '/media/hotel_images/hyatt_regency_mumbai.jpg'),
(2, 'Renaissance Mumbai Convention Centre Hotel', '2 & 3B, Near Chinmayanand Ashram, Powai, Mumbai, 400087', 4.3, 11000.00, '/media/hotel_images/renaissance_mumbai.jpg'),
(2, 'The Lalit Mumbai', 'Sahar Airport Road, Andheri East, Mumbai, 400059', 4.3, 10500.00, '/media/hotel_images/lalit_mumbai.jpg');

-- Venues for Mumbai
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(2, 'NESCO Centre', 'Western Express Highway, Goregaon East, Mumbai, 400063', 5000, 600000.00, '/media/venue_images/nesco_centre.jpg'),
(2, 'Jio World Convention Centre', 'BKC, Bandra East, Mumbai, 400051', 8000, 1000000.00, '/media/venue_images/jio_world_convention.jpg'),
(2, 'Dome @ NSCI', 'Worli, Mumbai, 400018', 4000, 550000.00, '/media/venue_images/dome_nsci.jpg'),
(2, 'Taj Lands End Grand Ballroom', 'Bandstand, Bandra West, Mumbai, 400050', 1200, 350000.00, '/media/venue_images/taj_lands_end_ballroom.jpg'),
(2, 'The St. Regis Mumbai Grand Ballroom', '462, Senapati Bapat Marg, Lower Parel, Mumbai, 400013', 1000, 380000.00, '/media/venue_images/st_regis_grand_ballroom.jpg'),
(2, 'Bombay Exhibition Centre', 'NESCO Complex, Western Express Highway, Goregaon East, Mumbai, 400063', 10000, 1200000.00, '/media/venue_images/bombay_exhibition_centre.jpg'),
(2, 'Royal Western India Turf Club', 'Mahalaxmi Racecourse, Keshavrao Khadye Marg, Royal Western India Turf Club, Mumbai, 400034', 3000, 500000.00, '/media/venue_images/royal_western_turf_club.jpg'),
(2, 'Wankhede Stadium', 'D Road, Churchgate, Mumbai, 400020', 33000, 1500000.00, '/media/venue_images/wankhede_stadium.jpg'),
(2, 'Grand Hyatt Mumbai Grand Ballroom', 'Off Western Express Highway, Santacruz East, Mumbai, 400055', 1500, 400000.00, '/media/venue_images/grand_hyatt_ballroom.jpg'),
(2, 'Nehru Centre Auditorium', 'Dr. Annie Besant Road, Worli, Mumbai, 400018', 1000, 300000.00, '/media/venue_images/nehru_centre_auditorium.jpg'),
(2, 'The Lalit Mumbai Great Eastern Ballroom', 'Sahar Airport Road, Andheri East, Mumbai, 400059', 800, 250000.00, '/media/venue_images/lalit_great_eastern_ballroom.jpg'),
(2, 'JW Marriott Mumbai Juhu Grand Ballroom', 'Juhu Tara Road, Juhu Beach, Mumbai, 400049', 900, 320000.00, '/media/venue_images/jw_marriott_juhu_ballroom.jpg'),
(2, 'Renaissance Mumbai Convention Centre', '2 & 3B, Near Chinmayanand Ashram, Powai, Mumbai, 400087', 1800, 420000.00, '/media/venue_images/renaissance_convention_centre.jpg'),
(2, 'Shanmukhananda Hall', 'Sion East, Mumbai, 400022', 2800, 350000.00, '/media/venue_images/shanmukhananda_hall.jpg'),
(2, 'Manik Sabhagruh', 'Bandra Reclamation, Bandra West, Mumbai, 400050', 1200, 280000.00, '/media/venue_images/manik_sabhagruh.jpg'),
(2, 'World Trade Centre Mumbai', 'Cuffe Parade, Mumbai, 400005', 1500, 350000.00, '/media/venue_images/world_trade_centre_mumbai.jpg'),
(2, 'Courtyard by Marriott Mumbai International Airport', 'CTS 215, Andheri Kurla Road, Andheri East, Mumbai, 400059', 700, 200000.00, '/media/venue_images/courtyard_marriott_mumbai.jpg'),
(2, 'Sofitel Mumbai BKC Grand Ballroom', 'C-57, Bandra Kurla Complex, Bandra East, Mumbai, 400051', 850, 280000.00, '/media/venue_images/sofitel_bkc_ballroom.jpg'),
(2, 'Cooperage Football Stadium', 'Maharshi Karve Road, Churchgate, Mumbai, 400020', 10000, 800000.00, '/media/venue_images/cooperage_stadium.jpg'),
(2, 'DY Patil Stadium', 'Nerul, Navi Mumbai, 400706', 55000, 2000000.00, '/media/venue_images/dy_patil_stadium.jpg');

-- ==================== BANGALORE ====================
-- Tourism Places for Bangalore
INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(3, 'Lalbagh Botanical Garden', 'A 240-acre garden designed in the style of Mughal Gardens. Home to India''s largest collection of tropical plants, a glass house, and a lake.', '/media/place_images/lalbagh_botanical_garden.jpg'),
(3, 'Bangalore Palace', 'Built in 1887, this palace was inspired by England''s Windsor Castle. Features Tudor-style architecture with fortified towers, arches, and green lawns.', '/media/place_images/bangalore_palace.jpg'),
(3, 'Cubbon Park', 'A landmark 300-acre lung space of Bangalore, home to diverse species of plants and trees. Features several neo-classical styled government buildings.', '/media/place_images/cubbon_park.jpg'),
(3, 'Vidhana Soudha', 'The seat of Karnataka''s state legislature, this imposing granite building is one of the best examples of Neo-Dravidian architecture and incorporates elements of Indo-Saracenic and Dravidian styles.', '/media/place_images/vidhana_soudha.jpg'),
(3, 'ISKCON Temple Bangalore', 'One of the largest ISKCON temples in the world, known for its blend of modern technology and spiritual tradition. The temple is built in a unique blend of contemporary and traditional styles.', '/media/place_images/iskcon_temple_bangalore.jpg'),
(3, 'Bannerghatta National Park', 'A biological reserve that also contains a zoo, a pet corner, an animal rescue center, a butterfly enclosure, an aquarium, a snake house, and a safari park.', '/media/place_images/bannerghatta_national_park.jpg'),
(3, 'Tipu Sultan''s Summer Palace', 'An example of Indo-Islamic architecture, this palace was the summer residence of Tipu Sultan. It is entirely made of teak wood with finely embellished arches, pillars, and balconies.', '/media/place_images/tipu_sultan_summer_palace.jpg'),
(3, 'Wonderla Amusement Park', 'One of the largest amusement parks in India, featuring water rides, land rides, and a musical fountain. A perfect place for family entertainment.', '/media/place_images/wonderla_amusement_park.jpg'),
(3, 'Ulsoor Lake', 'One of the largest lakes in Bangalore, spread over an area of 125 acres. Popular for boating and features a walking path around its perimeter.', '/media/place_images/ulsoor_lake.jpg'),
(3, 'Nandi Hills', 'An ancient hill fortress located about 60 km from Bangalore. Known for its scenic beauty, sunrise views, and historical monuments.', '/media/place_images/nandi_hills.jpg'),
(3, 'National Gallery of Modern Art', 'Housed in a colonial mansion, this gallery showcases modern and contemporary art from India and around the world.', '/media/place_images/national_gallery_modern_art.jpg'),
(3, 'HAL Aerospace Museum', 'India''s first aerospace museum, showcasing the history of HAL and India''s aviation industry. Features aircraft models, flight simulators, and engines.', '/media/place_images/hal_aerospace_museum.jpg'),
(3, 'Bull Temple', 'A 16th-century temple dedicated to Nandi Bull (the mount of Lord Shiva). Features a large monolithic statue of Nandi.', '/media/place_images/bull_temple.jpg'),
(3, 'Innovative Film City', 'An entertainment theme park featuring replicas of famous monuments, a wax museum, a dinosaur world, and various other attractions.', '/media/place_images/innovative_film_city.jpg'),
(3, 'Karnataka Chitrakala Parishath', 'An art complex featuring multiple galleries that showcase paintings, sculptures, and folk art from across India.', '/media/place_images/karnataka_chitrakala_parishath.jpg'),
(3, 'Freedom Park', 'A former central jail that has been converted into a recreational area with museums, exhibition spaces, and a meditation center.', '/media/place_images/freedom_park.jpg'),
(3, 'Jawaharlal Nehru Planetarium', 'A planetarium that offers various shows about astronomy and space science. Also houses an interactive science park.', '/media/place_images/jawaharlal_nehru_planetarium.jpg'),
(3, 'St. Mary''s Basilica', 'The oldest church in Bangalore, known for its Gothic-style architecture. Famous for the annual St. Mary''s Feast.', '/media/place_images/st_marys_basilica.jpg'),
(3, 'Commercial Street', 'A major shopping area in the Central Business District of Bangalore. Known for its mix of branded showrooms and street-side shops.', '/media/place_images/commercial_street.jpg');

-- Hotels for Bangalore
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(3, 'The Leela Palace Bangalore', '23, Old Airport Road, Bengaluru, 560008', 4.8, 18000.00, '/media/hotel_images/leela_palace_bangalore.jpg'),
(3, 'Taj West End', 'Race Course Road, Bengaluru, 560001', 4.7, 16000.00, '/media/hotel_images/taj_west_end.jpg'),
(3, 'ITC Gardenia', '1, Residency Road, Bengaluru, 560025', 4.7, 15000.00, '/media/hotel_images/itc_gardenia.jpg'),
(3, 'The Oberoi Bengaluru', '37-39, Mahatma Gandhi Road, Bengaluru, 560001', 4.8, 17000.00, '/media/hotel_images/oberoi_bengaluru.jpg'),
(3, 'JW Marriott Hotel Bengaluru', '24/1, Vittal Mallya Road, Bengaluru, 560001', 4.6, 14000.00, '/media/hotel_images/jw_marriott_bengaluru.jpg'),
(3, 'Shangri-La Hotel Bengaluru', '56-6B, Palace Road, Bengaluru, 560052', 4.6, 13500.00, '/media/hotel_images/shangri_la_bengaluru.jpg'),
(3, 'The Ritz-Carlton Bangalore', '99, Residency Road, Bengaluru, 560025', 4.7, 15500.00, '/media/hotel_images/ritz_carlton_bangalore.jpg'),
(3, 'Taj MG Road', '41/3, Mahatma Gandhi Road, Bengaluru, 560001', 4.5, 12000.00, '/media/hotel_images/taj_mg_road.jpg'),
(3, 'Four Seasons Hotel Bengaluru', '8, Bellary Road, Bengaluru, 560032', 4.6, 14000.00, '/media/hotel_images/four_seasons_bengaluru.jpg'),
(3, 'Vivanta Bengaluru Residency Road', '66, Residency Road, Bengaluru, 560025', 4.4, 10000.00, '/media/hotel_images/vivanta_residency_road.jpg'),
(3, 'Radisson Blu Atria Bengaluru', '1, Palace Road, Bengaluru, 560001', 4.3, 9000.00, '/media/hotel_images/radisson_blu_atria.jpg'),
(3, 'The Lalit Ashok', 'Kumara Krupa High Grounds, Bengaluru, 560001', 4.4, 11000.00, '/media/hotel_images/lalit_ashok.jpg'),
(3, 'Hyatt Centric MG Road Bangalore', '1/1, Swami Vivekananda Road, Bengaluru, 560008', 4.3, 9500.00, '/media/hotel_images/hyatt_centric_mg_road.jpg'),
(3, 'Conrad Bengaluru', '25/3, Kensington Road, Bengaluru, 560008', 4.5, 12500.00, '/media/hotel_images/conrad_bengaluru.jpg'),
(3, 'Sheraton Grand Bangalore Hotel at Brigade Gateway', '26/1, Dr. Rajkumar Road, Bengaluru, 560055', 4.5, 12000.00, '/media/hotel_images/sheraton_grand_bangalore.jpg'),
(3, 'Taj Yeshwantpur', '2275, Tumkur Road, Bengaluru, 560022', 4.4, 10500.00, '/media/hotel_images/taj_yeshwantpur.jpg'),
(3, 'Royal Orchid Central', '47/1, Dickenson Road, Bengaluru, 560042', 4.2, 8000.00, '/media/hotel_images/royal_orchid_central.jpg'),
(3, 'The Park Bangalore', '14/7, Mahatma Gandhi Road, Bengaluru, 560001', 4.1, 7500.00, '/media/hotel_images/the_park_bangalore.jpg'),
(3, 'Lemon Tree Premier', '2/1, St. John''s Road, Bengaluru, 560042', 4.2, 8500.00, '/media/hotel_images/lemon_tree_premier.jpg'),
(3, 'Aloft Bengaluru Cessna Business Park', 'Cessna Business Park, Bengaluru, 560087', 4.3, 9000.00, '/media/hotel_images/aloft_cessna_business_park.jpg');

-- Venues for Bangalore
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(3, 'Bangalore International Exhibition Centre', '10th Mile, Tumkur Road, Bengaluru, 562123', 10000, 800000.00, '/media/venue_images/bangalore_international_exhibition.jpg'),
(3, 'Palace Grounds', 'Jayamahal Main Road, Bengaluru, 560006', 15000, 1000000.00, '/media/venue_images/palace_grounds.jpg'),
(3, 'Manpho Convention Centre', 'Nagawara, Bengaluru, 560045', 5000, 600000.00, '/media/venue_images/manpho_convention_centre.jpg'),
(3, 'The Leela Palace Grand Ballroom', '23, Old Airport Road, Bengaluru, 560008', 1000, 350000.00, '/media/venue_images/leela_palace_grand_ballroom.jpg'),
(3, 'JW Marriott Hotel Bengaluru Grand Ballroom', '24/1, Vittal Mallya Road, Bengaluru, 560001', 900, 320000.00, '/media/venue_images/jw_marriott_bengaluru_ballroom.jpg'),
(3, 'The Taj West End Garden', 'Race Course Road, Bengaluru, 560001', 800, 280000.00, '/media/venue_images/taj_west_end_garden.jpg'),
(3, 'M. Chinnaswamy Stadium', 'Mahatma Gandhi Road, Bengaluru, 560001', 40000, 1800000.00, '/media/venue_images/chinnaswamy_stadium.jpg'),
(3, 'Bangalore Palace Grounds', 'Jayamahal Main Road, Bengaluru, 560006', 5000, 500000.00, '/media/venue_images/bangalore_palace_grounds.jpg'),
(3, 'The Ritz-Carlton Ballroom', '99, Residency Road, Bengaluru, 560025', 750, 300000.00, '/media/venue_images/ritz_carlton_ballroom.jpg'),
(3, 'Sheraton Grand Bengaluru Whitefield Convention Center', 'ITPL Main Road, Bengaluru, 560066', 2000, 450000.00, '/media/venue_images/sheraton_whitefield_convention.jpg'),
(3, 'Jayamahal Palace Hotel Gardens', 'Jayamahal Main Road, Bengaluru, 560046', 1200, 350000.00, '/media/venue_images/jayamahal_palace_gardens.jpg'),
(3, 'Conrad Bengaluru Grand Ballroom', '25/3, Kensington Road, Bengaluru, 560008', 800, 290000.00, '/media/venue_images/conrad_bengaluru_ballroom.jpg'),
(3, 'Taj Yeshwantpur Grand Ballroom', '2275, Tumkur Road, Bengaluru, 560022', 700, 260000.00, '/media/venue_images/taj_yeshwantpur_ballroom.jpg'),
(3, 'The Lalit Ashok Lawn', 'Kumara Krupa High Grounds, Bengaluru, 560001', 1500, 380000.00, '/media/venue_images/lalit_ashok_lawn.jpg'),
(3, 'ITC Gardenia Grand Ballroom', '1, Residency Road, Bengaluru, 560025', 850, 310000.00, '/media/venue_images/itc_gardenia_ballroom.jpg'),
(3, 'The Oterra Convention Centre', 'Electronics City, Bengaluru, 560100', 1800, 400000.00, '/media/venue_images/oterra_convention_centre.jpg'),
(3, 'Royal Orchid Resort and Convention Centre', 'Bellary Road, Bengaluru, 560065', 2500, 500000.00, '/media/venue_images/royal_orchid_convention.jpg'),
(3, 'The Grand Magrath', 'Magrath Road, Bengaluru, 560025', 600, 220000.00, '/media/venue_images/grand_magrath.jpg'),
(3, 'Shangri-La Hotel Grand Ballroom', '56-6B, Palace Road, Bengaluru, 560052', 750, 280000.00, '/media/venue_images/shangri_la_grand_ballroom.jpg'),
(3, 'Kanteerava Indoor Stadium', 'Kasturba Road, Bengaluru, 560001', 5000, 600000.00, '/media/venue_images/kanteerava_indoor_stadium.jpg');

-- ==================== CHENNAI ====================
-- Tourism Places for Chennai
INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(4, 'Marina Beach', 'The second-longest urban beach in the world stretching 13 km along the Bay of Bengal. Features a lighthouse, statues, and is a popular spot for sunrise views.', '/media/place_images/marina_beach.jpg'),
(4, 'Kapaleeshwarar Temple', 'A 7th-century Dravidian-style temple dedicated to Lord Shiva. Known for its ornate gopuram (tower) and is an important pilgrimage site.', '/media/place_images/kapaleeshwarar_temple.jpg'),
(4, 'Fort St. George', 'Built in 1644 by the British East India Company, it was the first English fortress in India. Houses St. Mary''s Church and a museum with colonial artifacts.', '/media/place_images/fort_st_george.jpg'),
(4, 'Government Museum', 'One of the oldest museums in India, established in 1851. Features a diverse collection including archaeology, numismatics, zoology, and natural history.', '/media/place_images/government_museum.jpg'),
(4, 'Santhome Cathedral Basilica', 'Built in the 16th century by Portuguese explorers, this Gothic-style cathedral is believed to house the tomb of St. Thomas the Apostle.', '/media/place_images/santhome_cathedral.jpg'),
(4, 'Elliot''s Beach', 'Also known as Besant Nagar Beach, this quiet and clean beach is less crowded than Marina Beach. Features the Karl Schmidt Memorial and water sports facilities.', '/media/place_images/elliots_beach.jpg'),
(4, 'Guindy National Park', 'One of the smallest national parks in India, located in the heart of Chennai. Home to various species of deer, jackals, and over 100 species of birds.', '/media/place_images/guindy_national_park.jpg'),
(4, 'Valluvar Kottam', 'A monument dedicated to the Tamil poet and philosopher Thiruvalluvar. Built in the shape of a temple chariot, it features all 1,330 verses of his work, Thirukkural.', '/media/place_images/valluvar_kottam.jpg'),
(4, 'Cholamandal Artists'' Village', 'India''s largest artists'' commune, established in 1966. Features galleries, open-air theaters, and artists'' studios.', '/media/place_images/cholamandal_artists_village.jpg'),
(4, 'Birla Planetarium', 'One of the oldest planetariums in India, offering shows on astronomy and space science. Also houses an astronomy museum.', '/media/place_images/birla_planetarium.jpg'),
(4, 'DakshinaChitra', 'A living museum of art, architecture, lifestyle, and performing arts of South India. Features traditional houses from various South Indian states.', '/media/place_images/dakshinachitra.jpg'),
(4, 'MGR Film City', 'A film studio and amusement park named after the former Tamil Nadu Chief Minister and actor, M.G. Ramachandran. Features shooting locations and entertainment options.', '/media/place_images/mgr_film_city.jpg'),
(4, 'VGP Universal Kingdom', 'An amusement and water park with various rides, attractions, and entertainment options. Located near the beach.', '/media/place_images/vgp_universal_kingdom.jpg'),
(4, 'Thousand Lights Mosque', 'A prominent mosque built in the early 19th century. Named for the 1,000 oil lamps that supposedly light its main hall.', '/media/place_images/thousand_lights_mosque.jpg'),
(4, 'Arignar Anna Zoological Park', 'Also known as Vandalur Zoo, this 1,300-acre facility is one of the largest zoos in South Asia. Home to over 170 species of mammals, birds, and reptiles.', '/media/place_images/arignar_anna_zoological_park.jpg'),
(4, 'Parthasarathy Temple', 'One of the oldest temples in Chennai dedicated to Lord Krishna. Built during the 8th century by the Pallavas.', '/media/place_images/parthasarathy_temple.jpg'),
(4, 'Chennai Rail Museum', 'Showcases the heritage of the Southern Railway. Features vintage locomotives, coaches, and exhibits on the history of Indian Railways.', '/media/place_images/chennai_rail_museum.jpg'),
(4, 'Theosophical Society', 'Headquartered in Chennai, this spiritual organization has a beautiful garden campus with a 450-year-old banyan tree and a library.', '/media/place_images/theosophical_society.jpg'),
(4, 'Vivekananda House', 'Also known as Ice House, this is where Swami Vivekananda stayed during his visit to Chennai. Now a museum dedicated to his life and teachings.', '/media/place_images/vivekananda_house.jpg'),
(4, 'Tiger Cave', 'An 8th-century rock-cut Hindu temple complex located near Mamallapuram. Named for the tiger-shaped carvings that adorn the entrance.', '/media/place_images/tiger_cave.jpg');

-- Hotels for Chennai
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(4, 'ITC Grand Chola', '63, Mount Road, Guindy, Chennai, 600032', 4.8, 15000.00, '/media/hotel_images/itc_grand_chola.jpg'),
(4, 'The Leela Palace Chennai', 'Adyar Seaface, MRC Nagar, Chennai, 600028', 4.7, 14000.00, '/media/hotel_images/leela_palace_chennai.jpg'),
(4, 'Taj Coromandel', '37, Mahatma Gandhi Road, Nungambakkam, Chennai, 600034', 4.6, 12000.00, '/media/hotel_images/taj_coromandel.jpg'),
(4, 'The Park Chennai', '601, Anna Salai, Chennai, 600006', 4.5, 10000.00, '/media/hotel_images/the_park_chennai.jpg'),
(4, 'Hyatt Regency Chennai', '365, Anna Salai, Teynampet, Chennai, 600018', 4.6, 11000.00, '/media/hotel_images/hyatt_regency_chennai.jpg'),
(4, 'Trident Chennai', '1/24, GST Road, Chennai, 600016', 4.5, 9500.00, '/media/hotel_images/trident_chennai.jpg'),
(4, 'Radisson Blu Hotel GRT', 'No. 531, GST Road, St. Thomas Mount, Chennai, 600016', 4.4, 9000.00, '/media/hotel_images/radisson_blu_grt.jpg'),
(4, 'The Residency Towers', '115, Sir Thyagaraya Road, T. Nagar, Chennai, 600017', 4.4, 8500.00, '/media/hotel_images/residency_towers.jpg'),
(4, 'Taj Fisherman''s Cove Resort & Spa', 'Covelong Beach, East Coast Road, Chennai, 603112', 4.7, 13000.00, '/media/hotel_images/taj_fishermans_cove.jpg'),
(4, 'Novotel Chennai Chamiers Road', '11, Chamiers Road, Nandanam, Chennai, 600035', 4.3, 8000.00, '/media/hotel_images/novotel_chamiers_road.jpg'),
(4, 'Hilton Chennai', '124/1, JN Salai, Guindy, Chennai, 600032', 4.5, 9500.00, '/media/hotel_images/hilton_chennai.jpg'),
(4, 'Courtyard by Marriott Chennai', '564, Anna Salai, Teynampet, Chennai, 600018', 4.4, 8500.00, '/media/hotel_images/courtyard_marriott_chennai.jpg'),
(4, 'The Westin Chennai Velachery', 'Velachery Main Road, Velachery, Chennai, 600042', 4.6, 10500.00, '/media/hotel_images/westin_chennai.jpg'),
(4, 'Welcomhotel by ITC Hotels', '22, Cathedral Road, Chennai, 600086', 4.3, 8000.00, '/media/hotel_images/welcomhotel_chennai.jpg'),
(4, 'Hablis Hotel', '19, GST Road, Guindy, Chennai, 600032', 4.2, 7500.00, '/media/hotel_images/hablis_hotel.jpg'),
(4, 'The Raintree, Anna Salai', '636, Anna Salai, Teynampet, Chennai, 600035', 4.3, 8000.00, '/media/hotel_images/raintree_anna_salai.jpg'),
(4, 'Grand Chennai by GRT Hotels', '120, Sir Thyagaraya Road, T. Nagar, Chennai, 600017', 4.2, 7000.00, '/media/hotel_images/grand_chennai.jpg'),
(4, 'Somerset Greenways Chennai', '94, Sathyadev Avenue, MRC Nagar, Chennai, 600028', 4.3, 7500.00, '/media/hotel_images/somerset_greenways.jpg'),
(4, 'Lemon Tree Hotel Chennai', '72, Sardar Patel Road, Guindy, Chennai, 600032', 4.1, 6500.00, '/media/hotel_images/lemon_tree_chennai.jpg'),
(4, 'Turyaa Chennai', '144/7, Rajiv Gandhi Salai, Old Mahabalipuram Road, Chennai, 600096', 4.2, 7000.00, '/media/hotel_images/turyaa_chennai.jpg');

-- Venues for Chennai
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(4, 'Chennai Trade Centre', 'TNPF Complex, Mount Poonamallee Road, Nandambakkam, Chennai, 600089', 5000, 600000.00, '/media/venue_images/chennai_trade_centre.jpg'),
(4, 'Chennai Convention Centre', 'ITC Grand Chola, 63, Mount Road, Guindy, Chennai, 600032', 2500, 500000.00, '/media/venue_images/chennai_convention_centre.jpg'),
(4, 'Leela Palace Ballroom', 'Adyar Seaface, MRC Nagar, Chennai, 600028', 1200, 350000.00, '/media/venue_images/leela_palace_ballroom.jpg'),
(4, 'The Taj Coromandel Grand Ballroom', '37, Mahatma Gandhi Road, Nungambakkam, Chennai, 600034', 800, 280000.00, '/media/venue_images/taj_coromandel_ballroom.jpg'),
(4, 'Chennai Nehru Indoor Stadium', 'Chennai, 600003', 8000, 750000.00, '/media/venue_images/nehru_indoor_stadium.jpg'),
(4, 'Hyatt Regency Grand Ballroom', '365, Anna Salai, Teynampet, Chennai, 600018', 900, 300000.00, '/media/venue_images/hyatt_regency_ballroom.jpg'),
(4, 'Mayor Radhakrishnan Stadium', 'Egmore, Chennai, 600008', 5000, 500000.00, '/media/venue_images/mayor_radhakrishnan_stadium.jpg'),
(4, 'YMCA Grounds', 'Royapettah, Chennai, 600014', 3000, 350000.00, '/media/venue_images/ymca_grounds.jpg'),
(4, 'Feathers Convention Centre', 'Maraimalai Nagar, Chennai, 603209', 1800, 400000.00, '/media/venue_images/feathers_convention_centre.jpg'),
(4, 'The Westin Chennai Grand Ballroom', 'Velachery Main Road, Velachery, Chennai, 600042', 700, 250000.00, '/media/venue_images/westin_chennai_ballroom.jpg'),
(4, 'Jawaharlal Nehru Outdoor Stadium', 'Periamet, Chennai, 600003', 40000, 1500000.00, '/media/venue_images/jawaharlal_nehru_stadium.jpg'),
(4, 'Radisson Blu Hotel GRT Convention Centre', 'No. 531, GST Road, St. Thomas Mount, Chennai, 600016', 1000, 300000.00, '/media/venue_images/radisson_blu_convention.jpg'),
(4, 'Green Park Convention Centre', 'Green Park Hotel, NSK Salai, Vadapalani, Chennai, 600026', 1200, 320000.00, '/media/venue_images/green_park_convention.jpg'),
(4, 'VGP Golden Beach Resort', 'East Coast Road, Chennai, 600041', 2000, 450000.00, '/media/venue_images/vgp_golden_beach.jpg'),
(4, 'MGM Beach Resort', 'East Coast Road, Muttukadu, Chennai, 603112', 1500, 380000.00, '/media/venue_images/mgm_beach_resort.jpg'),
(4, 'Chennai Citi Centre', 'Dr. Radhakrishnan Salai, Mylapore, Chennai, 600004', 1000, 300000.00, '/media/venue_images/chennai_citi_centre.jpg'),
(4, 'The Residency Towers Convention Hall', '115, Sir Thyagaraya Road, T. Nagar, Chennai, 600017', 600, 200000.00, '/media/venue_images/residency_towers_hall.jpg'),
(4, 'Hilton Chennai Grand Ballroom', '124/1, JN Salai, Guindy, Chennai, 600032', 700, 250000.00, '/media/venue_images/hilton_chennai_ballroom.jpg'),
(4, 'Anna Centenary Library Auditorium', 'Gandhi Mandapam Road, Kotturpuram, Chennai, 600085', 1000, 280000.00, '/media/venue_images/anna_centenary_library.jpg'),
(4, 'MA Chidambaram Stadium', 'Chepauk, Chennai, 600005', 50000, 2000000.00, '/media/venue_images/ma_chidambaram_stadium.jpg');

INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(5, 'Victoria Memorial', 'A large marble building built between 1906 and 1921 dedicated to the memory of Queen Victoria.', '/media/place_images/victoria_memorial.jpg'),
(5, 'Howrah Bridge', 'A cantilever bridge with a suspended span over the Hooghly River, commissioned in 1943.', '/media/place_images/howrah_bridge.jpg'),
(5, 'Indian Museum', 'The largest and oldest museum in India, established in 1814.', '/media/place_images/indian_museum.jpg'),
(5, 'Science City', 'The largest science center in the Indian subcontinent.', '/media/place_images/science_city.jpg'),
(5, 'Dakshineswar Kali Temple', 'A Hindu temple located on the eastern bank of the Hooghly River.', '/media/place_images/dakshineswar_kali_temple.jpg'),
(5, 'Eco Park', 'An urban park featuring various ecological zones and recreational facilities.', '/media/place_images/eco_park.jpg'),
(5, 'Marble Palace', 'A 19th century mansion built in neoclassical style, housing art collections.', '/media/place_images/marble_palace.jpg'),
(5, 'South Park Street Cemetery', 'A historic cemetery established in 1767 featuring Gothic and Indo-Saracenic style tombs.', '/media/place_images/south_park_street_cemetery.jpg'),
(5, 'Alipore Zoo', 'India''s oldest formally stated zoological park, established in 1876.', '/media/place_images/alipore_zoo.jpg'),
(5, 'Nicco Park', 'An amusement park known as the "Disneyland of West Bengal".', '/media/place_images/nicco_park.jpg'),
(5, 'College Street', 'A historic street famous for its bookstores and the prestigious Presidency College.', '/media/place_images/college_street.jpg'),
(5, 'Eden Gardens', 'One of the most iconic cricket stadiums in the world.', '/media/place_images/eden_gardens.jpg'),
(5, 'Belur Math', 'The headquarters of the Ramakrishna Math and Mission, founded by Swami Vivekananda.', '/media/place_images/belur_math.jpg'),
(5, 'Mother House', 'The headquarters of the Missionaries of Charity, founded by Mother Teresa.', '/media/place_images/mother_house.jpg'),
(5, 'Jorasanko Thakur Bari', 'The ancestral home of the Tagore family, now a museum dedicated to Rabindranath Tagore.', '/media/place_images/jorasanko_thakur_bari.jpg'),
(5, 'St. Paul''s Cathedral', 'A Gothic Revival cathedral built in 1847.', '/media/place_images/st_pauls_cathedral.jpg'),
(5, 'Maidan', 'The largest urban park in Kolkata, often called the "lungs of Kolkata".', '/media/place_images/maidan.jpg'),
(5, 'New Market', 'A historic marketplace established in 1874, now a popular shopping destination.', '/media/place_images/new_market.jpg'),
(5, 'Tagore''s House', 'The house where Rabindranath Tagore was born and spent most of his life.', '/media/place_images/tagores_house.jpg'),
(5, 'Botanical Gardens', 'Home to the 250-year-old Great Banyan Tree and over 12,000 plant species.', '/media/place_images/botanical_gardens.jpg');

-- Hotels in Kolkata
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(5, 'The Oberoi Grand', '15, Jawaharlal Nehru Road, Kolkata 700013', 4.8, 12500.00, '/media/hotel_images/oberoi_grand.jpg'),
(5, 'ITC Royal Bengal', '1 JBS Haldane Avenue, Kolkata 700046', 4.7, 11000.00, '/media/hotel_images/itc_royal_bengal.jpg'),
(5, 'Taj Bengal', '34B Belvedere Road, Alipore, Kolkata 700027', 4.6, 10500.00, '/media/hotel_images/taj_bengal.jpg'),
(5, 'The Park Kolkata', '17 Park Street, Kolkata 700016', 4.3, 8000.00, '/media/hotel_images/the_park_kolkata.jpg'),
(5, 'Novotel Kolkata', 'CF 11, Action Area 1C, New Town, Kolkata 700156', 4.4, 7500.00, '/media/hotel_images/novotel_kolkata.jpg'),
(5, 'JW Marriott Kolkata', '4A, J.B.S. Haldane Avenue, Kolkata 700105', 4.5, 9500.00, '/media/hotel_images/jw_marriott_kolkata.jpg'),
(5, 'Hyatt Regency Kolkata', 'JA-1, Sector III, Salt Lake City, Kolkata 700098', 4.2, 8500.00, '/media/hotel_images/hyatt_regency_kolkata.jpg'),
(5, 'The Lalit Great Eastern', '1-3 Old Court House Street, Kolkata 700069', 4.1, 7000.00, '/media/hotel_images/lalit_great_eastern.jpg'),
(5, 'Fairfield by Marriott', 'CB 218, Action Area 1C, New Town, Kolkata 700156', 4.0, 5500.00, '/media/hotel_images/fairfield_marriott.jpg'),
(5, 'The Sonnet Kolkata', '8 Block DD, Sector 1, Salt Lake, Kolkata 700064', 3.9, 4500.00, '/media/hotel_images/sonnet_kolkata.jpg'),
(5, 'Lemon Tree Premier', 'Plot No.X-4, Block EP, Sector V, Salt Lake, Kolkata 700091', 4.0, 5000.00, '/media/hotel_images/lemon_tree_premier.jpg'),
(5, 'The HHI Kolkata', '235/1 AJC Bose Road, Kolkata 700020', 3.8, 4000.00, '/media/hotel_images/hhi_kolkata.jpg'),
(5, 'Kenilworth Hotel', '1&2 Little Russel Street, Kolkata 700071', 3.9, 4200.00, '/media/hotel_images/kenilworth_hotel.jpg'),
(5, 'Aauris Hotel', 'EA Block, Sector 1, Salt Lake, Kolkata 700064', 3.7, 3800.00, '/media/hotel_images/aauris_hotel.jpg'),
(5, 'The Fern Residency', 'Plot No. IID/1, Action Area II-D, New Town, Kolkata 700156', 3.8, 4100.00, '/media/hotel_images/fern_residency.jpg'),
(5, 'Howard Johnson Kolkata', 'New Town, Action Area 1D, Biswa Bangla Sarani, Kolkata 700156', 3.6, 3600.00, '/media/hotel_images/howard_johnson.jpg'),
(5, 'Fortune Park Panchwati', '1 R.N. Mukherjee Road, Kolkata 700001', 3.7, 3900.00, '/media/hotel_images/fortune_park_panchwati.jpg'),
(5, 'The Senator Hotel', '15 Shakespeare Sarani, Kolkata 700071', 3.5, 3500.00, '/media/hotel_images/senator_hotel.jpg'),
(5, 'De Sovrani', '27 A, Ballygunge Circular Road, Kolkata 700019', 3.6, 3700.00, '/media/hotel_images/de_sovrani.jpg'),
(5, 'The Lindsay', '8A Lindsay Street, New Market Area, Kolkata 700087', 3.4, 3200.00, '/media/hotel_images/lindsay_hotel.jpg');

-- Venues in Kolkata
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(5, 'Netaji Indoor Stadium', 'Eden Gardens, Strand Road, Kolkata 700001', 12000, 75000.00, '/media/venue_images/netaji_indoor_stadium.jpg'),
(5, 'Science City Convention Centre', 'JBS Haldane Avenue, East Topsia, Kolkata 700046', 3000, 50000.00, '/media/venue_images/science_city_convention.jpg'),
(5, 'Biswa Bangla Convention Centre', 'DG Block, Action Area I, New Town, Kolkata 700156', 3200, 60000.00, '/media/venue_images/biswa_bangla_convention.jpg'),
(5, 'The Oberoi Grand Ballroom', 'The Oberoi Grand, 15 Jawaharlal Nehru Road, Kolkata 700013', 500, 150000.00, '/media/venue_images/oberoi_grand_ballroom.jpg'),
(5, 'ITC Royal Bengal Grand Ballroom', 'ITC Royal Bengal, 1 JBS Haldane Avenue, Kolkata 700046', 650, 180000.00, '/media/venue_images/itc_royal_ballroom.jpg'),
(5, 'Taj Bengal Emerald Hall', 'Taj Bengal, 34B Belvedere Road, Alipore, Kolkata 700027', 450, 140000.00, '/media/venue_images/taj_bengal_emerald.jpg'),
(5, 'Swabhumi Heritage Plaza', 'Swabhumi, 89C Moulana Abul Kalam Azad Sarani, Kolkata 700054', 2000, 45000.00, '/media/venue_images/swabhumi_heritage.jpg'),
(5, 'Eastern Zonal Cultural Centre', 'IB-201, Sector III, Salt Lake City, Kolkata 700106', 1500, 35000.00, '/media/venue_images/ezcc.jpg'),
(5, 'Rabindra Sadan', 'Cathedral Road, Maidan, Kolkata 700071', 1200, 30000.00, '/media/venue_images/rabindra_sadan.jpg'),
(5, 'Nicco Park Banquet', 'Jheel Meel, Sector IV, Salt Lake, Kolkata 700098', 1000, 40000.00, '/media/venue_images/nicco_park_banquet.jpg'),
(5, 'JW Marriott Grand Ballroom', 'JW Marriott, 4A JBS Haldane Avenue, Kolkata 700105', 550, 175000.00, '/media/venue_images/jw_marriott_ballroom.jpg'),
(5, 'Eco Park Banquet', 'Major Arterial Road, AA IIB, Newtown, Kolkata 700156', 800, 38000.00, '/media/venue_images/eco_park_banquet.jpg'),
(5, 'Hyatt Regency Regency Ballroom', 'JA-1 Sector III, Salt Lake City, Kolkata 700098', 500, 145000.00, '/media/venue_images/hyatt_regency_ballroom.jpg'),
(5, 'Khudiram Anushilan Kendra', '5, Narkeldanga Main Road, Kankurgachi, Kolkata 700054', 2500, 42000.00, '/media/venue_images/khudiram_kendra.jpg'),
(5, 'The Westin Kolkata Grand Ballroom', 'Plot No CBD/2, Action Area II, New Town, Kolkata 700156', 600, 160000.00, '/media/venue_images/westin_ballroom.jpg'),
(5, 'Ganga Kutir Banquet', 'Fern Place, Raichak, Kolkata 743368', 300, 85000.00, '/media/venue_images/ganga_kutir.jpg'),
(5, 'Vedic Village Convention Hall', 'Shikharpur Village, Rajarhat, Kolkata 700135', 1200, 65000.00, '/media/venue_images/vedic_village.jpg'),
(5, 'Calcutta Rowing Club', '15-N, Rabindra Sarobar, Kolkata 700029', 350, 75000.00, '/media/venue_images/rowing_club.jpg'),
(5, 'Novotel Kolkata Ballroom', 'CF 11, Action Area 1C, New Town, Kolkata 700156', 450, 130000.00, '/media/venue_images/novotel_ballroom.jpg'),
(5, 'Bengal Club Heritage Hall', '33, Chowringhee Road, Kolkata 700071', 250, 90000.00, '/media/venue_images/bengal_club.jpg');

-- HYDERABAD (City ID: 2)
-- Tourism Places in Hyderabad
INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(6, 'Charminar', 'A monument and mosque built in 1591, a symbol of Hyderabad.', '/media/place_images/charminar.jpg'),
(6, 'Golconda Fort', 'A medieval fort and citadel, once the capital of the Qutb Shahi dynasty.', '/media/place_images/golconda_fort.jpg'),
(6, 'Ramoji Film City', 'World''s largest integrated film city and tourism destination.', '/media/place_images/ramoji_film_city.jpg'),
(6, 'Hussain Sagar Lake', 'Heart-shaped artificial lake built in 1562, featuring a monolithic statue of Buddha.', '/media/place_images/hussain_sagar.jpg'),
(6, 'Salar Jung Museum', 'One of the three National Museums of India with collections from around the world.', '/media/place_images/salar_jung_museum.jpg'),
(6, 'Birla Mandir', 'A Hindu temple built on a hilltop with white marble architecture.', '/media/place_images/birla_mandir.jpg'),
(6, 'Qutb Shahi Tombs', 'A collection of tombs and mosques built by the Qutb Shahi dynasty.', '/media/place_images/qutb_shahi_tombs.jpg'),
(6, 'Falaknuma Palace', 'A luxury palace hotel that was once owned by the Nizams of Hyderabad.', '/media/place_images/falaknuma_palace.jpg'),
(6, 'Lumbini Park', 'An urban park near Hussain Sagar lake featuring laser shows and boating.', '/media/place_images/lumbini_park.jpg'),
(6, 'Nehru Zoological Park', 'One of the largest zoos in India with a diverse range of animals and birds.', '/media/place_images/nehru_zoo.jpg'),
(6, 'Chowmahalla Palace', 'Once the seat of the Asaf Jahi dynasty, known for its unique architecture.', '/media/place_images/chowmahalla_palace.jpg'),
(6, 'Chilkur Balaji Temple', 'Also known as Visa Balaji Temple, famous for granting visa wishes.', '/media/place_images/chilkur_balaji_temple.jpg'),
(6, 'NTR Gardens', 'An urban park developed in memory of N. T. Rama Rao.', '/media/place_images/ntr_gardens.jpg'),
(6, 'Taramati Baradari', 'A historical caravanserai built during Ibrahim Quli Qutb Shah''s reign.', '/media/place_images/taramati_baradari.jpg'),
(6, 'Shilparamam', 'A craft village showcasing traditional arts and crafts of India.', '/media/place_images/shilparamam.jpg'),
(6, 'Mecca Masjid', 'One of the largest mosques in India, built in the 17th century.', '/media/place_images/mecca_masjid.jpg'),
(6, 'Warangal Fort', 'A historic fort built in the 12th century by the Kakatiya dynasty.', '/media/place_images/warangal_fort.jpg'),
(6, 'Durgam Cheruvu', 'A serene lake also known as Secret Lake, offering recreational activities.', '/media/place_images/durgam_cheruvu.jpg'),
(6, 'Osman Sagar', 'A reservoir also known as Gandipet Lake, built during the reign of the last Nizam.', '/media/place_images/osman_sagar.jpg'),
(6, 'Bhongir Fort', 'A historic fort built on a monolithic rock dating back to the 10th century.', '/media/place_images/bhongir_fort.jpg');

-- Hotels in Hyderabad
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(6, 'Taj Falaknuma Palace', 'Engine Bowli, Falaknuma, Hyderabad 500053', 4.9, 25000.00, '/media/hotel_images/taj_falaknuma.jpg'),
(6, 'Taj Krishna', 'Road No 1, Banjara Hills, Hyderabad 500034', 4.7, 12000.00, '/media/hotel_images/taj_krishna.jpg'),
(6, 'ITC Kohenur', 'Plot No. 5, Survey No. 83/1, Hyderabad Knowledge City, Hyderabad 500081', 4.8, 15000.00, '/media/hotel_images/itc_kohenur.jpg'),
(6, 'The Park Hyderabad', '22, Raj Bhavan Road, Somajiguda, Hyderabad 500082', 4.5, 8500.00, '/media/hotel_images/park_hyderabad.jpg'),
(6, 'Novotel Hyderabad Convention Centre', 'Novotel & HICC Complex, Near Hitec City, Hyderabad 500081', 4.4, 7500.00, '/media/hotel_images/novotel_hyderabad.jpg'),
(6, 'Radisson Blu Plaza', '8-2-409, Road No. 6, Banjara Hills, Hyderabad 500034', 4.3, 7000.00, '/media/hotel_images/radisson_blu_plaza.jpg'),
(6, 'Trident Hyderabad', 'Hitech City, Near Cyber Towers, Hyderabad 500081', 4.6, 9500.00, '/media/hotel_images/trident_hyderabad.jpg'),
(6, 'The Westin Hyderabad Mindspace', 'Raheja IT Park, Mindspace, Madhapur, Hyderabad 500081', 4.5, 9000.00, '/media/hotel_images/westin_hyderabad.jpg'),
(6, 'Hyatt Hyderabad Gachibowli', 'Road No. 2, Banjara Hills, Hyderabad 500034', 4.4, 8000.00, '/media/hotel_images/hyatt_hyderabad.jpg'),
(6, 'Courtyard by Marriott Hyderabad', '1-3-1024/1 Lower Tank Bund Road, Hyderabad 500080', 4.2, 6500.00, '/media/hotel_images/courtyard_marriott.jpg'),
(6, 'Lemon Tree Premier', 'Survey No. 115/1, Gachibowli, Hyderabad 500032', 4.0, 5500.00, '/media/hotel_images/lemon_tree_hyderabad.jpg'),
(6, 'Vivanta Hyderabad Begumpet', '1-10-147 & 148, Mayuri Marg, Begumpet, Hyderabad 500016', 4.1, 6000.00, '/media/hotel_images/vivanta_hyderabad.jpg'),
(6, 'Mercure Hyderabad KCP', '6-3-551, Somajiguda, Hyderabad 500082', 3.9, 5000.00, '/media/hotel_images/mercure_hyderabad.jpg'),
(6, 'Taj Deccan', 'Road No. 1, Banjara Hills, Hyderabad 500034', 4.3, 7200.00, '/media/hotel_images/taj_deccan.jpg'),
(6, 'Sheraton Hyderabad Hotel', '115/1, IT Park, Nanakramguda, Gachibowli, Hyderabad 500008', 4.2, 6800.00, '/media/hotel_images/sheraton_hyderabad.jpg'),
(6, 'Marigold by Greenpark', '7-1-25, Greenlands, Begumpet, Hyderabad 500016', 3.8, 4500.00, '/media/hotel_images/marigold_greenpark.jpg'),
(6, 'Aditya Park', 'Aditya Trade Centre, Ameerpet, Hyderabad 500038', 3.7, 4000.00, '/media/hotel_images/aditya_park.jpg'),
(6, 'The Golkonda Hotel', '10-1-124, Masab Tank, Hyderabad 500028', 3.9, 4800.00, '/media/hotel_images/golkonda_hotel.jpg'),
(6, 'Minerva Grand', '8-2-616/1, Road No. 11, Banjara Hills, Hyderabad 500034', 3.6, 3800.00, '/media/hotel_images/minerva_grand.jpg'),
(6, 'Alankrita Resort', 'Survey No. 70, Thumkunta Village, Shamirpet, Hyderabad 500078', 4.0, 5200.00, '/media/hotel_images/alankrita_resort.jpg');

-- Venues in Hyderabad
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(6, 'Hyderabad International Convention Centre', 'Novotel & HICC Complex, Hyderabad 500081', 5000, 200000.00, '/media/venue_images/hicc.jpg'),
(6, 'Hitex Exhibition Centre', 'HITEX, Kothaguda, Hyderabad 500084', 4000, 150000.00, '/media/venue_images/hitex.jpg'),
(6, 'Taj Krishna Grand Ballroom', 'Road No. 1, Banjara Hills, Hyderabad 500034', 800, 180000.00, '/media/venue_images/taj_krishna_ballroom.jpg'),
(6, 'ITC Kohenur Grand Ballroom', 'Plot No. 5, Survey No. 83/1, Knowledge City, Hyderabad 500081', 1000, 220000.00, '/media/venue_images/itc_kohenur_ballroom.jpg'),
(6, 'N Convention', 'Survey No. 31/2, Raviryala Village, Rangareddy, Hyderabad 501510', 2500, 120000.00, '/media/venue_images/n_convention.jpg'),
(6, 'Shilpakala Vedika', 'Hitec City Road, Madhapur, Hyderabad 500081', 2500, 110000.00, '/media/venue_images/shilpakala_vedika.jpg'),
(6, 'Trident Hyderabad Ballroom', 'Hitech City, Near Cyber Towers, Hyderabad 500081', 600, 160000.00, '/media/venue_images/trident_ballroom.jpg'),
(6, 'The Westin Hyderabad Ballroom', 'Raheja IT Park, Mindspace, Madhapur, Hyderabad 500081', 700, 175000.00, '/media/venue_images/westin_ballroom.jpg'),
(6, 'Ramoji Film City Venues', 'Ramoji Film City, Hyderabad 501512', 3000, 250000.00, '/media/venue_images/ramoji_venues.jpg'),
(6, 'KLN Prasad Auditorium', 'FTAPCCI, Red Hills, Hyderabad 500004', 800, 70000.00, '/media/venue_images/kln_prasad.jpg'),
(6, 'Aalankrita Resort Conference Hall', 'Survey No. 70, Thumkunta Village, Shamirpet, Hyderabad 500078', 500, 65000.00, '/media/venue_images/aalankrita_hall.jpg'),
(6, 'Boulder Hills Club', 'Gachibowli, Hyderabad 500032', 600, 145000.00, '/media/venue_images/boulder_hills.jpg'),
(6, 'Novotel Hyderabad Ballroom', 'Novotel & HICC Complex, Near Hitec City, Hyderabad 500081', 550, 150000.00, '/media/venue_images/novotel_ballroom_hyd.jpg'),
(6, 'Marriott Hyderabad Convention Centre', 'Tank Bund Road, Hyderabad 500080', 650, 170000.00, '/media/venue_images/marriott_convention.jpg'),
(6, 'Hyatt Hyderabad Gachibowli Ballroom', 'Road No. 2, Banjara Hills, Hyderabad 500034', 500, 140000.00, '/media/venue_images/hyatt_ballroom_hyd.jpg'),
(6, 'Ellaa Hotels Convention Centre', 'Hill Ridge Springs, Gachibowli, Hyderabad 500032', 750, 130000.00, '/media/venue_images/ellaa_convention.jpg'),
(6, 'Taj Falaknuma Palace Durbar Hall', 'Engine Bowli, Falaknuma, Hyderabad 500053', 300, 350000.00, '/media/venue_images/falaknuma_durbar.jpg'),
(6, 'Leonia Holistic Destination', 'Survey No. 50, Bommaraspet Village, Hyderabad 508126', 1500, 200000.00, '/media/venue_images/leonia_holistic.jpg'),
(6, 'Avasa Hotel Ballroom', 'Plot No. 15, 24, 25 & 26, Survey No. 64, HITEC City, Hyderabad 500081', 450, 135000.00, '/media/venue_images/avasa_ballroom.jpg'),
(6, 'Taramati Baradari Cultural Complex', 'Ibrahim Bagh, Hyderabad 500008', 1000, 90000.00, '/media/venue_images/taramati_complex.jpg');

-- PUNE (City ID: 3)
-- Tourism Places in Pune
INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(7, 'Shaniwar Wada', 'Historic fortification in the city, built in 1732 as the seat of the Peshwas.', '/media/place_images/shaniwar_wada.jpg'),
(7, 'Aga Khan Palace', 'A majestic building built in 1892, with historical significance from the freedom movement.', '/media/place_images/aga_khan_palace.jpg'),
(7, 'Dagdusheth Halwai Ganpati Temple', 'One of the most visited Ganesh temples in Maharashtra.', '/media/place_images/dagdusheth_ganpati.jpg'),
(7, 'Sinhagad Fort', 'An ancient fortress located on a hill about 30 km from Pune city.', '/media/place_images/sinhagad_fort.jpg'),
(7, 'Lal Mahal', 'A historic palace built by Shahaji Bhonsle for his wife and son Shivaji in 1630.', '/media/place_images/lal_mahal.jpg'),
(7, 'Osho Ashram', 'International meditation resort founded by spiritual leader Osho.', '/media/place_images/osho_ashram.jpg'),
(7, 'Pataleshwar Cave Temple', 'Rock-cut cave temple dating back to the 8th century.', '/media/place_images/pataleshwar_cave.jpg'),
(7, 'Raja Dinkar Kelkar Museum', 'Houses the collection of Dr. Dinkar G. Kelkar with over 20,000 artifacts.', '/media/place_images/kelkar_museum.jpg'),
(7, 'Parvati Hill Temple', 'Located on Parvati Hill, offering panoramic views of Pune city.', '/media/place_images/parvati_hill.jpg'),
(7, 'Shinde Chhatri', 'Memorial to 18th century military leader Mahadji Shinde, known for its architecture.', '/media/place_images/shinde_chhatri.jpg'),
(7, 'Katraj Snake Park', 'A zoo and snake park housing a variety of reptiles and animals.', '/media/place_images/katraj_snake_park.jpg'),
(7, 'Saras Baug', 'A large park surrounding the Ganesh temple, built on a lake.', '/media/place_images/saras_baug.jpg'),
(7, 'Mulshi Dam', 'A scenic dam surrounded by lush greenery and hills.', '/media/place_images/mulshi_dam.jpg'),
(7, 'Khadakwasla Dam', 'A dam on the Mutha River that supplies water to Pune city.', '/media/place_images/khadakwasla_dam.jpg'),
(7, 'Tribal Museum', 'A museum dedicated to showcasing tribal heritage and culture.', '/media/place_images/tribal_museum.jpg'),
(7, 'National War Museum', 'Dedicated to the warriors who sacrificed their lives for the country.', '/media/place_images/war_museum.jpg'),
(7, 'Bund Garden', 'A garden with a riverside promenade along the Mula-Mutha river.', '/media/place_images/bund_garden.jpg'),
(7, 'Empress Botanical Garden', 'A historic botanical garden dating back to the British era.', '/media/place_images/empress_garden.jpg'),
(7, 'Rajiv Gandhi Zoological Park', 'A modern zoo with various animal and bird species.', '/media/place_images/rajiv_gandhi_zoo.jpg'),
(7, 'Pune-Okayama Friendship Garden', 'The largest Japanese garden in India, known as Pu La Deshpande Udyan.', '/media/place_images/pune_okayama_garden.jpg');

-- Hotels in Pune
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(7, 'The Conrad Pune', '7 Mangaldas Road, Pune 411001', 4.7, 12000.00, '/media/hotel_images/conrad_pune.jpg'),
(7, 'JW Marriott Hotel Pune', 'Senapati Bapat Road, Pune 411053', 4.6, 11000.00, '/media/hotel_images/jw_marriott_pune.jpg'),
(7, 'The Westin Pune', '36/3-B Koregaon Park Annexe, Pune 411001', 4.5, 10000.00, '/media/hotel_images/westin_pune.jpg'),
(7, 'Hyatt Pune', '88 Nagar Road, Pune 411014', 4.4, 9000.00, '/media/hotel_images/hyatt_pune.jpg'),
(7, 'Sheraton Grand Pune', 'Raja Bahadur Mill Road, Pune 411001', 4.5, 9500.00, '/media/hotel_images/sheraton_pune.jpg'),
(7, 'Novotel Pune', 'Weikfield IT Park, Pune 411014', 4.3, 8500.00, '/media/hotel_images/novotel_pune.jpg'),
(7, 'Ritz-Carlton Pune', 'Golf Course Square, Pune 411001', 4.8, 14000.00, '/media/hotel_images/ritz_carlton_pune.jpg'),
(7, 'Crowne Plaza Pune', 'City Centre, Bund Garden Road, Pune 411001', 4.2, 7800.00, '/media/hotel_images/crowne_plaza_pune.jpg'),
(7, 'Marriott Suites Pune', 'Koregaon Park Annexe, Pune 411001', 4.4, 9200.00, '/media/hotel_images/marriott_suites_pune.jpg'),
(7, 'The Pride Hotel', 'University Road, Shivajinagar, Pune 411005', 4.0, 6500.00, '/media/hotel_images/pride_hotel_pune.jpg'),
(7, 'Royal Orchid Central', 'Kalyani Nagar, Pune 411006', 4.1, 7000.00, '/media/hotel_images/royal_orchid_pune.jpg'),
(7, 'Lemon Tree Premier', 'City Center, Pune 411001', 4.0, 6800.00, '/media/hotel_images/lemon_tree_pune.jpg'),
(7, 'Ramee Grand Hotel', 'Apte Road, Pune 411004', 3.9, 6300.00, '/media/hotel_images/ramee_grand_pune.jpg'),
(7, 'Blue Diamond IHCL', 'Koregaon Park Road, Pune 411001', 4.2, 7500.00, '/media/hotel_images/blue_diamond_pune.jpg'),
(7, 'Four Points by Sheraton', 'Nagar Road, Pune 411014', 4.1, 7200.00, '/media/hotel_images/four_points_pune.jpg'),
(7, 'Oakwood Residence', 'Mundhwa Road, Pune 411036', 4.0, 6600.00, '/media/hotel_images/oakwood_residence_pune.jpg'),
(7, 'Ibis Pune', 'Viman Nagar, Pune 411014', 3.8, 5000.00, '/media/hotel_images/ibis_pune.jpg'),
(7, 'The Central Park Hotel', 'Bund Garden Road, Pune 411001', 3.7, 4800.00, '/media/hotel_images/central_park_pune.jpg'),
(7, 'Hotel Sagar Plaza', 'Bund Garden Road, Pune 411001', 3.6, 4500.00, '/media/hotel_images/sagar_plaza_pune.jpg'),
(7, 'Kapila Business Hotel', 'Koregaon Park, Pune 411001', 3.5, 4200.00, '/media/hotel_images/kapila_business_pune.jpg');

-- Venues in Pune
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(7, 'Yashwantrao Chavan Auditorium', 'Kothrud, Pune 411038', 2000, 100000.00, '/media/venue_images/yashwantrao_chavan.jpg'),
(7, 'The Orchid Hotel Convention Centre', 'Balewadi High Street, Pune 411045', 1500, 120000.00, '/media/venue_images/orchid_convention.jpg'),
(7, 'JW Marriott Grand Ballroom', 'Senapati Bapat Road, Pune 411053', 900, 190000.00, '/media/venue_images/jw_marriott_ballroom_pune.jpg'),
(7, 'The Conrad Ballroom', '7 Mangaldas Road, Pune 411001', 750, 175000.00, '/media/venue_images/conrad_ballroom_pune.jpg'),
(7, 'Balgandharva Rangmandir', 'J.M. Road, Pune 411004', 1000, 55000.00, '/media/venue_images/balgandharva_rangmandir.jpg'),
(7, 'The Corinthians Resort', 'NIBM Annexe, Pune 411060', 800, 140000.00, '/media/venue_images/corinthians_resort.jpg'),
(7, 'Hyatt Pune Ballroom', '88 Nagar Road, Pune 411014', 650, 150000.00, '/media/venue_images/hyatt_ballroom_pune.jpg'),
(7, 'The Westin Pune Grand Ballroom', '36/3-B Koregaon Park Annexe, Pune 411001', 700, 165000.00, '/media/venue_images/westin_ballroom_pune.jpg'),
(7, 'Sheraton Grand Pune Convention', 'Raja Bahadur Mill Road, Pune 411001', 750, 160000.00, '/media/venue_images/sheraton_convention_pune.jpg'),
(7, 'Symbiosis Vishwabhavan Auditorium', 'Senapati Bapat Road, Pune 411004', 1200, 70000.00, '/media/venue_images/symbiosis_auditorium.jpg'),
(7, 'Amanora Park Town', 'Hadapsar, Pune 411028', 1500, 110000.00, '/media/venue_images/amanora_park.jpg'),
(7, 'Ritz-Carlton Ballroom', 'Golf Course Square, Pune 411001', 600, 200000.00, '/media/venue_images/ritz_carlton_ballroom_pune.jpg'),
(7, 'Royal Palms', 'Koregaon Park, Pune 411001', 1000, 130000.00, '/media/venue_images/royal_palms_pune.jpg'),
(7, 'The Pride Hotel Conference Hall', 'University Road, Shivajinagar, Pune 411005', 550, 95000.00, '/media/venue_images/pride_conference_pune.jpg'),
(7, 'Novotel Pune Convention', 'Weikfield IT Park, Pune 411014', 600, 120000.00, '/media/venue_images/novotel_convention_pune.jpg'),
(7, 'Aga Khan Palace Grounds', 'Nagar Road, Pune 411006', 2000, 85000.00, '/media/venue_images/aga_khan_grounds.jpg'),
(7, 'Oxford Golf Resort', 'Bavdhan, Pune 411021', 800, 150000.00, '/media/venue_images/oxford_golf_resort.jpg'),
(7, 'Crowne Plaza Convention Centre', 'City Centre, Bund Garden Road, Pune 411001', 700, 140000.00, '/media/venue_images/crowne_plaza_convention_pune.jpg'),
(7, 'Peshwe Park Amphitheatre', 'Sahakar Nagar, Pune 411009', 1500, 60000.00, '/media/venue_images/peshwe_park.jpg'),
(7, 'Mahalakshmi Lawns', 'Karve Road, Pune 411038', 2500, 90000.00, '/media/venue_images/mahalakshmi_lawns.jpg');

-- JAIPUR (City ID: 4)
-- Tourism Places in Jaipur
INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(8, 'Amber Fort', 'A majestic fort known for its artistic Hindu style elements, situated on a hill.', '/media/place_images/amber_fort.jpg'),
(8, 'Hawa Mahal', 'The Palace of Winds, a five-story palace built in 1799 with a unique honeycomb facade.', '/media/place_images/hawa_mahal.jpg'),
(8, 'City Palace', 'A palace complex with a museum, courtyards, and gardens, still partly a royal residence.', '/media/place_images/city_palace_jaipur.jpg'),
(8, 'Jantar Mantar', 'UNESCO World Heritage site featuring the world''s largest stone sundial.', '/media/place_images/jantar_mantar.jpg'),
(8, 'Jal Mahal', 'A palace situated in the middle of Man Sagar Lake.', '/media/place_images/jal_mahal.jpg'),
(8, 'Nahargarh Fort', 'A fort overlooking the city, offering stunning views of Jaipur.', '/media/place_images/nahargarh_fort.jpg'),
(8, 'Albert Hall Museum', 'The oldest museum in Rajasthan, known for its Indo-Saracenic architecture.', '/media/place_images/albert_hall_museum.jpg'),
(8, 'Jaigarh Fort', 'A rugged fort built to protect Amber Fort, known for its large cannon.', '/media/place_images/jaigarh_fort.jpg'),
(8, 'Birla Mandir', 'A Hindu temple made of white marble, dedicated to Lord Vishnu and Goddess Lakshmi.', '/media/place_images/birla_mandir_jaipur.jpg'),
(8, 'Galta Ji', 'An ancient Hindu pilgrimage site known as Monkey Temple.', '/media/place_images/galta_ji.jpg'),
(8, 'Sisodia Rani Garden', 'A multi-tiered garden with fountains, built in 1728.', '/media/place_images/sisodia_rani_garden.jpg'),
(8, 'Chokhi Dhani', 'A Rajasthani ethnic village resort showcasing traditional culture.', '/media/place_images/chokhi_dhani.jpg'),
(8, 'Elefantastic', 'An elephant sanctuary offering ethical elephant experiences.', '/media/place_images/elefantastic.jpg'),
(8, 'Anokhi Museum', 'Dedicated to hand printing textiles, housed in a restored haveli.', '/media/place_images/anokhi_museum.jpg'),
(8, 'Central Park', 'The largest park in Jaipur with a musical fountain and walking tracks.', '/media/place_images/central_park_jaipur.jpg'),
(8, 'Govind Dev Ji Temple', 'A sacred temple dedicated to Lord Krishna, built in 1590.', '/media/place_images/govind_dev_ji.jpg'),
(8, 'Jawahar Circle Garden', 'The largest circular park in Asia with a musical fountain.', '/media/place_images/jawahar_circle.jpg'),
(8, 'Gatore Ki Chhatriyan', 'Cenotaphs of the royal family of Jaipur, featuring exquisite architecture.', '/media/place_images/gatore_ki_chhatriyan.jpg'),
(8, 'Amrapali Museum', 'A jewelry museum displaying a unique collection of tribal and traditional jewelry.', '/media/place_images/amrapali_museum.jpg'),
(8, 'Panna Meena Ka Kund', 'A step well with symmetrical stairs and a historical significance.', '/media/place_images/panna_meena_ka_kund.jpg');

-- Hotels in Jaipur
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(8, 'Taj Rambagh Palace', 'Bhawani Singh Road, Jaipur 302005', 4.9, 32000.00, '/media/hotel_images/rambagh_palace.jpg'),
(8, 'The Oberoi Rajvilas', 'Goner Road, Jaipur 302031', 4.8, 28000.00, '/media/hotel_images/oberoi_rajvilas.jpg'),
(8, 'ITC Rajputana', 'Palace Road, Jaipur 302006', 4.6, 12000.00, '/media/hotel_images/itc_rajputana.jpg'),
(8, 'Fairmont Jaipur', 'Riico Kukas, Jaipur 302028', 4.7, 15000.00, '/media/hotel_images/fairmont_jaipur.jpg'),
(8, 'Taj Jai Mahal Palace', 'Jacob Road, Civil Lines, Jaipur 302006', 4.7, 17000.00, '/media/hotel_images/taj_jai_mahal.jpg'),
(8, 'Marriott Jaipur', 'Ashram Marg, Near Jawahar Circle, Jaipur 302015', 4.5, 10000.00, '/media/hotel_images/marriott_jaipur.jpg'),
(8, 'Hilton Jaipur', 'Plot No. 42, Geejgarh House, Jaipur 302001', 4.4, 9000.00, '/media/hotel_images/hilton_jaipur.jpg'),
(8, 'Le Meridien Jaipur', 'RIICO Kukas, Jaipur 303101', 4.5, 11000.00, '/media/hotel_images/le_meridien_jaipur.jpg'),
(8, 'Radisson Blu Jaipur', 'Tonk Road, Jaipur 302018', 4.3, 8000.00, '/media/hotel_images/radisson_blu_jaipur.jpg'),
(8, 'Trident Jaipur', 'Amber Fort Road, Jaipur 302002', 4.6, 13000.00, '/media/hotel_images/trident_jaipur.jpg'),
(8, 'The Lalit Jaipur', '2B & 2C, Jagatpura Road, Jaipur 302017', 4.2, 7500.00, '/media/hotel_images/lalit_jaipur.jpg'),
(8, 'Holiday Inn Jaipur', 'Sardar Patel Marg, C-Scheme, Jaipur 302001', 4.0, 6000.00, '/media/hotel_images/holiday_inn_jaipur.jpg'),
(8, 'Fortune Select Metropolitan', 'Near Nehru Sahkar Bhawan, Jaipur 302005', 4.0, 5800.00, '/media/hotel_images/fortune_metropolitan.jpg'),
(8, 'Crowne Plaza Jaipur', 'Sitapura Industrial Area, Jaipur 302022', 4.3, 8200.00, '/media/hotel_images/crowne_plaza_jaipur.jpg'),
(8, 'Lemon Tree Premier', 'Nirwan Marg, Bani Park, Jaipur 302016', 4.1, 6500.00, '/media/hotel_images/lemon_tree_jaipur.jpg'),
(8, 'Fern Residency', 'Plot No 3, Tonk Road, Jaipur 302018', 3.9, 5200.00, '/media/hotel_images/fern_residency_jaipur.jpg'),
(8, 'Royal Orchid Central', 'A-26, A/2 Taj Enclave, Jaipur 302001', 3.8, 4800.00, '/media/hotel_images/royal_orchid_jaipur.jpg'),
(8, 'Ramada Jaipur', 'Govind Marg, Raja Park, Jaipur 302004', 3.7, 4500.00, '/media/hotel_images/ramada_jaipur.jpg'),
(8, 'Hotel Clarks Amer', 'JLN Marg, Jaipur 302018', 4.0, 5500.00, '/media/hotel_images/clarks_amer.jpg'),
(8, 'Sarovar Premiere', 'Tonk Road, Jaipur 302018', 3.9, 5000.00, '/media/hotel_images/sarovar_premiere.jpg');

-- Venues in Jaipur
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(8, 'Jaipur Exhibition & Convention Centre', 'EPIP, Sitapura Industrial Area, Jaipur 302022', 5000, 300000.00, '/media/venue_images/jecc.jpg'),
(8, 'Clarks Amer Convention Centre', 'JLN Marg, Jaipur 302018', 3000, 180000.00, '/media/venue_images/clarks_convention.jpg'),
(8, 'Fairmont Jaipur Grand Ballroom', 'Riico Kukas, Jaipur 302028', 1000, 250000.00, '/media/venue_images/fairmont_ballroom.jpg'),
(8, 'Taj Rambagh Palace Durbar Hall', 'Bhawani Singh Road, Jaipur 302005', 500, 450000.00, '/media/venue_images/rambagh_durbar.jpg'),
(8, 'Crowne Plaza Ballroom', 'Sitapura Industrial Area, Jaipur 302022', 800, 160000.00, '/media/venue_images/crowne_plaza_ballroom_jaipur.jpg'),
(8, 'The Lalit Grand Ballroom', '2B & 2C, Jagatpura Road, Jaipur 302017', 750, 140000.00, '/media/venue_images/lalit_ballroom_jaipur.jpg'),
(8, 'Marriott Jaipur Convention', 'Ashram Marg, Near Jawahar Circle, Jaipur 302015', 900, 180000.00, '/media/venue_images/marriott_convention_jaipur.jpg'),
(8, 'ITC Rajputana Grand Ballroom', 'Palace Road, Jaipur 302006', 650, 170000.00, '/media/venue_images/itc_ballroom_jaipur.jpg'),
(8, 'Birla Auditorium', 'Statue Circle, Jaipur 302005', 1500, 100000.00, '/media/venue_images/birla_auditorium.jpg'),
(8, 'Le Meridien Convention Centre', 'RIICO Kukas, Jaipur 303101', 700, 160000.00, '/media/venue_images/le_meridien_convention.jpg'),
(8, 'Jaipur Marriott Resort & Spa', 'Near Jaipur Airport, Jaipur 302029', 850, 170000.00, '/media/venue_images/marriott_resort_jaipur.jpg'),
(8, 'Oberoi Rajvilas Grand Tent', 'Goner Road, Jaipur 302031', 400, 350000.00, '/media/venue_images/rajvilas_tent.jpg'),
(8, 'Hilton Jaipur Ballroom', 'Plot No. 42, Geejgarh House, Jaipur 302001', 600, 150000.00, '/media/venue_images/hilton_ballroom_jaipur.jpg'),
(8, 'Trident Jaipur Convention Hall', 'Amber Fort Road, Jaipur 302002', 550, 160000.00, '/media/venue_images/trident_hall_jaipur.jpg'),
(8, 'Shiv Vilas Resort', 'Delhi Highway, Jaipur 303101', 900, 200000.00, '/media/venue_images/shiv_vilas_resort.jpg'),
(8, 'Jai Mahal Palace Durbar Hall', 'Jacob Road, Civil Lines, Jaipur 302006', 450, 280000.00, '/media/venue_images/jai_mahal_durbar.jpg'),
(8, 'Radisson Blu Convention Centre', 'Tonk Road, Jaipur 302018', 700, 140000.00, '/media/venue_images/radisson_convention_jaipur.jpg'),
(8, 'Jaivilas Palace', 'Jaleb Chowk, Amer, Jaipur 302028', 600, 250000.00, '/media/venue_images/jaivilas_palace.jpg'),
(8, 'Chomu Palace', 'Chomu, Jaipur 303702', 800, 180000.00, '/media/venue_images/chomu_palace.jpg'),
(8, 'Ramgarh Lodge', 'Ramgarh, Jaipur 302028', 350, 120000.00, '/media/venue_images/ramgarh_lodge.jpg');

INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(9, 'Sabarmati Ashram', 'Historic ashram of Mahatma Gandhi situated on the banks of Sabarmati River, offering insights into India''s freedom struggle and Gandhi''s life.', '/media/place_images/sabarmati_ashram.jpg'),
(9, 'Kankaria Lake', 'One of the largest lakes in Ahmedabad featuring a zoo, toy train, water rides, and balloon safari, perfect for family outings.', '/media/place_images/kankaria_lake.jpg'),
(9, 'Adalaj Stepwell', '15th-century five-story stepwell with intricate carvings that showcase the Indo-Islamic fusion architecture of Gujarat.', '/media/place_images/adalaj_stepwell.jpg'),
(9, 'ISKCON Temple', 'Beautiful temple dedicated to Lord Krishna, featuring exquisite architecture, peaceful atmosphere and spiritual activities.', '/media/place_images/iskcon_temple_ahmedabad.jpg'),
(9, 'Sarkhej Roza', 'Known as Ahmedabad''s Acropolis, this elegant architectural complex combines Hindu, Islamic, and Jain design elements.', '/media/place_images/sarkhej_roza.jpg'),
(9, 'Calico Museum of Textiles', 'World-renowned textile museum housing magnificent collection of rare textiles dating back several centuries.', '/media/place_images/calico_museum.jpg'),
(9, 'Jama Masjid', 'Built in 1424, this yellow sandstone mosque showcases a perfect blend of Hindu and Muslim architectural styles.', '/media/place_images/jama_masjid_ahmedabad.jpg'),
(9, 'Auto World Vintage Car Museum', 'Houses an impressive collection of vintage cars, buggies, and other automobiles from around the world.', '/media/place_images/auto_world_museum.jpg'),
(9, 'Law Garden', 'Popular market area known for traditional Gujarati handicrafts, garments, and delicious street food.', '/media/place_images/law_garden.jpg'),
(9, 'Akshardham Temple', 'Majestic Hindu temple complex featuring stunning architecture, exhibitions, and a spectacular water show.', '/media/place_images/akshardham_temple_ahmedabad.jpg'),
(9, 'Science City', 'Largest science center in Gujarat with interactive exhibits, an IMAX theater, and educational activities for all ages.', '/media/place_images/science_city_ahmedabad.jpg'),
(9, 'Sidi Saiyyed Mosque', 'Famous for its intricately carved stone lattice windows (jalis) depicting the "Tree of Life" motif.', '/media/place_images/sidi_saiyyed_mosque.jpg'),
(9, 'Vechaar Utensils Museum', 'Unique museum showcasing over 4,500 utensils made of various metals dating back to 18th century.', '/media/place_images/vechaar_museum.jpg'),
(9, 'Kamla Nehru Zoological Garden', 'Established in 1951, this zoo houses various species of mammals, birds, and reptiles in natural habitats.', '/media/place_images/kamla_nehru_zoo.jpg'),
(9, 'Dada Hari Ni Vav', '15th-century stepwell with intricate carvings and five stories that tell stories of mythology and history.', '/media/place_images/dada_hari_ni_vav.jpg'),
(9, 'Vastrapur Lake', 'Beautiful artificial lake with walking trails, gardens, and an open-air theater, popular among locals for evening strolls.', '/media/place_images/vastrapur_lake.jpg'),
(9, 'Rani Sipri''s Mosque', 'Also known as Masjid-e-Nagina (Jewel Mosque), famous for its delicate carvings and harmonious proportions.', '/media/place_images/rani_sipri_mosque.jpg'),
(9, 'Parimal Garden', 'Lush green garden with a variety of flowers, walkways, and play areas, ideal for morning walks and family outings.', '/media/place_images/parimal_garden.jpg'),
(9, 'Hutheesing Jain Temple', 'Built in 1848, this temple is dedicated to the 15th Jain Tirthankar and features intricate marble carvings.', '/media/place_images/hutheesing_jain_temple.jpg'),
(9, 'Bhadra Fort', 'Ancient fort complex housing government offices, a temple, and a royal palace with beautiful stone carvings.', '/media/place_images/bhadra_fort.jpg');

-- Insert Tourism Places for Kanpur
INSERT INTO tourism_tourismplace (city_id, name, description, image_url) VALUES
(10, 'JK Temple', 'Beautiful white marble temple dedicated to Lord Radha Krishna, featuring stunning architecture and peaceful surroundings.', '/media/place_images/jk_temple.jpg'),
(10, 'Kanpur Zoological Park', 'Sprawling zoo spread over 190 acres featuring diverse wildlife, reptile house, and botanical gardens.', '/media/place_images/kanpur_zoo.jpg'),
(10, 'Phool Bagh', 'Historic garden with monuments, fountains, and the Ganesh Shankar Vidyarthi Memorial dedicated to freedom fighters.', '/media/place_images/phool_bagh.jpg'),
(10, 'Allen Forest Zoo', 'Also known as the Kanpur Zoo, home to various species of animals, birds and reptiles in natural surroundings.', '/media/place_images/allen_forest_zoo.jpg'),
(10, 'Bithoor', 'Historic town on the banks of the Ganges river with numerous temples and sites related to Hindu mythology.', '/media/place_images/bithoor.jpg'),
(10, 'Jajmau', 'Ancient mound with historical significance dating back to the Vedic period, offers panoramic views of the Ganges.', '/media/place_images/jajmau.jpg'),
(10, 'Nana Rao Park', 'Historic park named after Nana Sahib of the 1857 rebellion, featuring colonial-era monuments and lush greenery.', '/media/place_images/nana_rao_park.jpg'),
(10, 'Blue World Theme Park', 'Modern water and amusement park offering various rides, water activities, and entertainment options for all ages.', '/media/place_images/blue_world_theme_park.jpg'),
(10, 'Moti Jheel', 'Picturesque lake surrounded by gardens, offering boating facilities and scenic views, popular for evening strolls.', '/media/place_images/moti_jheel.jpg'),
(10, 'Kanpur Memorial Church', 'Anglican church built in 1875 to commemorate the British who lost their lives during the 1857 uprising.', '/media/place_images/kanpur_memorial_church.jpg'),
(10, 'Bhitargaon Temple', 'Ancient brick temple from the Gupta period featuring terracotta panels depicting various mythological scenes.', '/media/place_images/bhitargaon_temple.jpg'),
(10, 'Valmiki Ashram', 'Ancient hermitage where sage Valmiki is believed to have composed the epic Ramayana.', '/media/place_images/valmiki_ashram.jpg'),
(10, 'ISKCON Temple Kanpur', 'Modern temple dedicated to Lord Krishna with beautiful architecture and spiritual atmosphere.', '/media/place_images/iskcon_temple_kanpur.jpg'),
(10, 'Shri Radhakrishna Temple', 'Popular temple with intricate architecture dedicated to Lord Krishna and Radha.', '/media/place_images/radhakrishna_temple.jpg'),
(10, 'Kamla Retreat', 'Scenic spot along the Ganges River with beautiful gardens and architectural features.', '/media/place_images/kamla_retreat.jpg'),
(10, 'Green Park Stadium', 'Famous cricket stadium that has hosted numerous international matches and is home to Uttar Pradesh cricket team.', '/media/place_images/green_park_stadium.jpg'),
(10, 'Boodha Bargad', 'Ancient banyan tree estimated to be over 200 years old with significant cultural importance.', '/media/place_images/boodha_bargad.jpg'),
(10, 'Sarsaiya Ghat', 'Scenic riverfront ghat on the banks of the Ganges, popular for religious ceremonies and evening walks.', '/media/place_images/sarsaiya_ghat.jpg'),
(10, 'Parivar Park', 'Family-friendly park with walking trails, play areas, and landscaped gardens.', '/media/place_images/parivar_park.jpg'),
(10, 'Gautam Buddha Park', 'Peaceful park with a large Buddha statue, perfect for meditation and relaxation.', '/media/place_images/gautam_buddha_park.jpg');

-- Insert Venues for Ahmedabad
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(9, 'Kensville Golf Club', 'Bavla, Ahmedabad District, Gujarat 382220', 1000, 150000.00, '/media/venue_images/kensville_golf_club.jpg'),
(9, 'Serenity Farm', 'Shela, Ahmedabad, Gujarat 380058', 1200, 85000.00, '/media/venue_images/serenity_farm.jpg'),
(9, 'Chokhi Dhani Resort', 'Sardar Patel Ring Road, Ahmedabad, Gujarat 380060', 2000, 200000.00, '/media/venue_images/chokhi_dhani_resort.jpg'),
(9, 'Club O7', 'Shela, Ahmedabad, Gujarat 380058', 1500, 175000.00, '/media/venue_images/club_o7.jpg'),
(9, 'The Grand Bhagwati', 'S G Highway, Ahmedabad, Gujarat 380054', 2500, 250000.00, '/media/venue_images/the_grand_bhagwati.jpg'),
(9, 'Ahmedabad Haat', 'Vastrapur, Ahmedabad, Gujarat 380015', 750, 50000.00, '/media/venue_images/ahmedabad_haat.jpg'),
(9, 'Karnavati Club', 'S G Highway, Ahmedabad, Gujarat 380015', 1800, 180000.00, '/media/venue_images/karnavati_club.jpg'),
(9, 'Gulmohar Greens', 'Satellite, Ahmedabad, Gujarat 380015', 1600, 160000.00, '/media/venue_images/gulmohar_greens.jpg'),
(9, 'AMA Auditorium', 'ATIRA Campus, Ahmedabad, Gujarat 380015', 500, 40000.00, '/media/venue_images/ama_auditorium.jpg'),
(9, 'TGB Convention Center', 'Makarba, Ahmedabad, Gujarat 380051', 3000, 300000.00, '/media/venue_images/tgb_convention_center.jpg'),
(9, 'Riverfront Flower Park', 'Sabarmati Riverfront, Ahmedabad, Gujarat 380009', 2000, 100000.00, '/media/venue_images/riverfront_flower_park.jpg'),
(9, 'Sports Club', 'Ahmedabad Cantonment, Gujarat 380004', 800, 60000.00, '/media/venue_images/sports_club.jpg'),
(9, 'Fortune Landmark', 'Usmanpura, Ahmedabad, Gujarat 380013', 1000, 120000.00, '/media/venue_images/fortune_landmark.jpg'),
(9, 'Vishalla', 'Vasna, Ahmedabad, Gujarat 380007', 600, 70000.00, '/media/venue_images/vishalla.jpg'),
(9, 'Narayani Heights', 'Gandhinagar Highway, Ahmedabad, Gujarat 382421', 1200, 140000.00, '/media/venue_images/narayani_heights.jpg'),
(9, 'Courtyard by Marriott', 'Satellite, Ahmedabad, Gujarat 380015', 900, 210000.00, '/media/venue_images/courtyard_by_marriott.jpg'),
(9, 'Hyatt Regency', 'Ashram Road, Ahmedabad, Gujarat 380014', 1100, 230000.00, '/media/venue_images/hyatt_regency.jpg'),
(9, 'Leela Lawns', 'Maninagar, Ahmedabad, Gujarat 380008', 700, 75000.00, '/media/venue_images/leela_lawns.jpg'),
(9, 'Ganesh Meridian', 'S G Highway, Ahmedabad, Gujarat 380060', 1300, 150000.00, '/media/venue_images/ganesh_meridian.jpg'),
(9, 'Pride Plaza Hotel', 'S G Highway, Ahmedabad, Gujarat 380054', 800, 190000.00, '/media/venue_images/pride_plaza_hotel.jpg');
-- Insert Venues for Kanpur
INSERT INTO tourism_venue (city_id, name, address, capacity, price_per_day, image_url) VALUES
(10, 'Landmark Hotel', 'The Mall Road, Kanpur, Uttar Pradesh 208001', 800, 70000.00, '/media/venue_images/landmark_hotel.jpg'),
(10, 'Mandakini Palace', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 1000, 85000.00, '/media/venue_images/mandakini_palace.jpg'),
(10, 'Z Square Mall', 'Mall Road, Kanpur, Uttar Pradesh 208001', 1500, 120000.00, '/media/venue_images/z_square_mall.jpg'),
(10, 'Riverview Retreat', 'Ganga Barrage, Kanpur, Uttar Pradesh 208017', 600, 65000.00, '/media/venue_images/riverview_retreat.jpg'),
(10, 'The Citi Club', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 700, 75000.00, '/media/venue_images/the_citi_club.jpg'),
(10, 'Regenta Central', 'Mall Road, Kanpur, Uttar Pradesh 208001', 900, 95000.00, '/media/venue_images/regenta_central.jpg'),
(10, 'Kanpur Golf Club', 'Kanpur Cantonment, Uttar Pradesh 208004', 500, 60000.00, '/media/venue_images/kanpur_golf_club.jpg'),
(10, 'Yashoda Heritage', 'Swaroop Nagar, Kanpur, Uttar Pradesh 208002', 400, 50000.00, '/media/venue_images/yashoda_heritage.jpg'),
(10, 'Shri Sahu Institute', 'G T Road, Kanpur, Uttar Pradesh 208005', 1200, 45000.00, '/media/venue_images/shri_sahu_institute.jpg'),
(10, 'JK Temple Grounds', 'Kamla Nagar, Kanpur, Uttar Pradesh 208005', 2000, 30000.00, '/media/venue_images/jk_temple_grounds.jpg'),
(10, 'Vijay Gardens', 'Kidwai Nagar, Kanpur, Uttar Pradesh 208011', 800, 55000.00, '/media/venue_images/vijay_gardens.jpg'),
(10, 'Gyan Bharti Convention', 'Mall Road, Kanpur, Uttar Pradesh 208001', 1000, 80000.00, '/media/venue_images/gyan_bharti_convention.jpg'),
(10, 'SKD Academy', 'Swaroop Nagar, Kanpur, Uttar Pradesh 208002', 2500, 70000.00, '/media/venue_images/skd_academy.jpg'),
(10, 'Allen Forest Lawns', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 600, 40000.00, '/media/venue_images/allen_forest_lawns.jpg'),
(10, 'Phool Bagh Grounds', 'Mall Road, Kanpur, Uttar Pradesh 208001', 1500, 35000.00, '/media/venue_images/phool_bagh_grounds.jpg'),
(10, 'Riverdale High', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 1000, 60000.00, '/media/venue_images/riverdale_high.jpg'),
(10, 'Jajmau Resort', 'Jajmau, Kanpur, Uttar Pradesh 208010', 700, 65000.00, '/media/venue_images/jajmau_resort.jpg'),
(10, 'Tatya Tope Nagar Stadium', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 3000, 90000.00, '/media/venue_images/tatya_tope_nagar_stadium.jpg'),
(10, 'Merchant Chamber Hall', 'The Mall Road, Kanpur, Uttar Pradesh 208001', 500, 45000.00, '/media/venue_images/merchant_chamber_hall.jpg'),
(10, 'Green Park Lawns', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 2000, 75000.00, '/media/venue_images/green_park_lawns.jpg');
-- Insert Hotels for Ahmedabad
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(9, 'The House of MG', 'Lal Darwaja, Ahmedabad, Gujarat 380001', 4.8, 8500.00, '/media/hotel_images/the_house_of_mg.jpg'),
(9, 'Hyatt Ahmedabad', 'Ashram Road, Ahmedabad, Gujarat 380014', 4.7, 9500.00, '/media/hotel_images/hyatt_ahmedabad.jpg'),
(9, 'ITC Narmada', 'Judges Bungalow Road, Ahmedabad, Gujarat 380015', 4.9, 12000.00, '/media/hotel_images/itc_narmada.jpg'),
(9, 'Novotel Ahmedabad', 'S G Highway, Ahmedabad, Gujarat 380054', 4.6, 7500.00, '/media/hotel_images/novotel_ahmedabad.jpg'),
(9, 'Renaissance Ahmedabad Hotel', 'S G Highway, Ahmedabad, Gujarat 380054', 4.7, 8900.00, '/media/hotel_images/renaissance_ahmedabad.jpg'),
(9, 'Crowne Plaza', 'S G Highway, Ahmedabad, Gujarat 380054', 4.5, 7800.00, '/media/hotel_images/crowne_plaza.jpg'),
(9, 'The Fern', 'Sola Road, Ahmedabad, Gujarat 380061', 4.3, 5500.00, '/media/hotel_images/the_fern.jpg'),
(9, 'Radisson Blu', 'Airport Road, Ahmedabad, Gujarat 380015', 4.6, 8000.00, '/media/hotel_images/radisson_blu.jpg'),
(9, 'Courtyard by Marriott', 'Satellite, Ahmedabad, Gujarat 380015', 4.8, 9800.00, '/media/hotel_images/courtyard_by_marriott.jpg'),
(9, 'Four Points by Sheraton', 'CG Road, Ahmedabad, Gujarat 380009', 4.5, 7600.00, '/media/hotel_images/four_points_by_sheraton.jpg'),
(9, 'Lemon Tree Premier', 'CG Road, Ahmedabad, Gujarat 380009', 4.4, 6500.00, '/media/hotel_images/lemon_tree_premier.jpg'),
(9, 'Pride Plaza Hotel', 'S G Highway, Ahmedabad, Gujarat 380054', 4.6, 8200.00, '/media/hotel_images/pride_plaza_hotel.jpg'),
(9, 'Ramada', 'Prahlad Nagar, Ahmedabad, Gujarat 380015', 4.2, 5800.00, '/media/hotel_images/ramada.jpg'),
(9, 'Fortune Landmark', 'Usmanpura, Ahmedabad, Gujarat 380013', 4.3, 6200.00, '/media/hotel_images/fortune_landmark.jpg'),
(9, 'Grand Mercure', 'S G Highway, Ahmedabad, Gujarat 380054', 4.7, 8700.00, '/media/hotel_images/grand_mercure.jpg'),
(9, 'Taj Skyline', 'Sindhu Bhavan Road, Ahmedabad, Gujarat 380059', 4.9, 12500.00, '/media/hotel_images/taj_skyline.jpg'),
(9, 'The Westend', 'S.G. Highway, Ahmedabad, Gujarat 380054', 4.4, 6800.00, '/media/hotel_images/the_westend.jpg'),
(9, 'Naeeka The Fern', 'S.G. Highway, Ahmedabad, Gujarat 380054', 4.2, 5900.00, '/media/hotel_images/naeeka_the_fern.jpg'),
(9, 'Caspia Hotel', 'CG Road, Ahmedabad, Gujarat 380009', 4.0, 4800.00, '/media/hotel_images/caspia_hotel.jpg'),
(9, 'Sarovar Portico', 'Shahibaug, Ahmedabad, Gujarat 380004', 4.1, 5200.00, '/media/hotel_images/sarovar_portico.jpg');
-- Insert Hotels for Kanpur
INSERT INTO tourism_hotel (city_id, name, address, rating, price_per_night, image_url) VALUES
(10, 'Landmark Towers', 'The Mall Road, Kanpur, Uttar Pradesh 208001', 4.3, 5500.00, '/media/hotel_images/landmark_towers.jpg'),
(10, 'Hotel Bliss', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 4.1, 4800.00, '/media/hotel_images/hotel_bliss.jpg'),
(10, 'The Piccadily', 'Mall Road, Kanpur, Uttar Pradesh 208001', 4.5, 6200.00, '/media/hotel_images/the_piccadily.jpg'),
(10, 'Hotel Royal Cliff', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 4.0, 4500.00, '/media/hotel_images/hotel_royal_cliff.jpg'),
(10, 'Regenta Central', 'Mall Road, Kanpur, Uttar Pradesh 208001', 4.2, 5800.00, '/media/hotel_images/regenta_central.jpg'),
(10, 'Hotel Vijay Intercontinental', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 3.9, 4200.00, '/media/hotel_images/hotel_vijay_intercontinental.jpg'),
(10, 'Mandakini Palace', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 4.0, 4600.00, '/media/hotel_images/mandakini_palace.jpg'),
(10, 'Hotel Ganges', 'Cantonment, Kanpur, Uttar Pradesh 208004', 3.8, 3800.00, '/media/hotel_images/hotel_ganges.jpg'),
(10, 'Citi Club & Suites', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 4.4, 5900.00, '/media/hotel_images/citi_club_and_suites.jpg'),
(10, 'Oyo Townhouse', 'Swaroop Nagar, Kanpur, Uttar Pradesh 208002', 3.7, 3500.00, '/media/hotel_images/oyo_townhouse.jpg'),
(10, 'Hotel Krishna Palace', 'Mall Road, Kanpur, Uttar Pradesh 208001', 3.9, 4100.00, '/media/hotel_images/hotel_krishna_palace.jpg'),
(10, 'Hotel Amber', 'Swaroop Nagar, Kanpur, Uttar Pradesh 208002', 3.8, 3900.00, '/media/hotel_images/hotel_amber.jpg'),
(10, 'Sky Blue Hotel', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 4.2, 5200.00, '/media/hotel_images/sky_blue_hotel.jpg'),
(10, 'Hotel Vibhuti', 'Gumti, Kanpur, Uttar Pradesh 208012', 3.6, 3400.00, '/media/hotel_images/hotel_vibhuti.jpg'),
(10, 'Hotel Ashok', 'Parade, Kanpur, Uttar Pradesh 208001', 4.0, 4500.00, '/media/hotel_images/hotel_ashok.jpg'),
(10, 'The G Hotel', 'Mall Road, Kanpur, Uttar Pradesh 208001', 4.3, 5700.00, '/media/hotel_images/the_g_hotel.jpg'),
(10, 'Hotel Sarovar', 'Swaroop Nagar, Kanpur, Uttar Pradesh 208002', 3.7, 3600.00, '/media/hotel_images/hotel_sarovar.jpg'),
(10, 'Treebo Trip Red Maple', 'Civil Lines, Kanpur, Uttar Pradesh 208001', 3.9, 4000.00, '/media/hotel_images/treebo_trip_red_maple.jpg'),
(10, 'Hotel Grand Riviera', 'Mall Road, Kanpur, Uttar Pradesh 208001', 4.1, 4900.00, '/media/hotel_images/hotel_grand_riviera.jpg'),
(10, 'Hotel Mahadeo', 'Arya Nagar, Kanpur, Uttar Pradesh 208002', 3.5, 3200.00, '/media/hotel_images/hotel_mahadeo.jpg');